### ISSUE TITLE
Any plans to support multiple linters per ft?

### ISSUE THREAD

**Issue by fsouza** [mfussenegger/nvim-lint#1]
This project is really exciting, I'm looking forward to ditch efm :)

I know this is extremely early-stage, but since I didn't see a todo note in the readme I figured I could open an issue: are there plans to support multiples linters per filetype?

**Comment by mfussenegger** [comment]
Good that you bring it up, I was actually wondering if that is something that should be supported :)

Do you have a concrete case in mind where you'd use multiple linters?
I also wonder which linters I should add first.

**Comment by fsouza** [comment]
Yeah I actually reviewed my config and I don't really use this anymore. I used to use mypy & flake8 for Python in the past though (mypy and any other typecheckers can be more difficult though, because they'll publish diagnostics for other files too, not just the one being "linted").

re: which linters to add, I was wondering if we could have something similar to efm/diagnosticls where the linter can be configured (along with some pattern to parse lines. not sure if that would work perfectly. Could also have a lower level API where the parser can be specified as a function, but I imagine most people would be ok with specifying a regexp/pattern?

**Comment by lourenci** [comment]
I'm all for it.

I'll use this plugin as soon as it gets support for eslint. :)

**Comment by mfussenegger** [comment]
> Yeah I actually reviewed my config and I don't really use this anymore 

😀
In any case, it shouldn't be too difficult to support running multiple linters per filetype.

> re: which linters to add, I was wondering if we could have something similar to efm/diagnosticls where the linter can be configured (along with some pattern to parse lines. not sure if that would work perfectly. Could also have a lower level API where the parser can be specified as a function, but I imagine most people would be ok with specifying a regexp/pattern?

Yes I had something like that in mind. The low-level API will operate on chunks and have a `done` method but there will be some factory functions to help generate a parser. A linter definition would then look somehow like this.


```lua
linter = {
  cmd = 'some_linter_cmd',
  args = {},
  parser = require('lint.parser').from_pattern('...')
}
```

Not sure yet how exactly this will look like but that's the general idea.

**Comment by mfussenegger** [comment]
With https://github.com/mfussenegger/nvim-lint/commit/0b99d4d048bb9f3b07e2a83e10ccf3711102167e running multiple linters should now work. (Though given that it turned out that I don't really like the languagetool results and there's otherwise now only `vale` available I didn't test it much) 

Having a `from_pattern` factory for parsers is still on the TODO because `vale` also supports json output and that seemed easier to use.
