### ISSUE TITLE
Integration with folke/trouble.nvim?

### ISSUE THREAD

**Issue by sbromberger** [mfussenegger/nvim-lint#123]
Thanks for a great plugin - just discovered it!

I've set up golangcilint and it's working properly. The only issue is the display. I use trouble.nvim to keep a quicklist of issues, but nvim-lint isn't using it the way I'd like.

First, the diagnostics are printed inline (which I don't want; see screenshot "lint1").

Second, lint results don't automatically toggle trouble (which I've set up to only appear if there are problems in the code). I have to type `:TroubleToggle` to get the results into the quickfix list.

Any ideas on how to fix these two (minor) usability issues?

<img width="1299" alt="lint1" src="https://user-images.githubusercontent.com/941359/144060502-d36ae4c2-333d-4dc9-86a2-3f54729f71f9.png">

**Comment by sbromberger** [comment]
I fixed the first issue by setting `vim.diagnostic.config({virtual_text = false})`. Still unsure how to get nvim-lint playing nicely with trouble.nvim.

**Comment by mfussenegger** [comment]
I think to toggle trouble you could either either create a `vim.diagnostic.handler`  (See `:help diagnostic-handlers`) or you can setup a `DiagnosticChanged` autocmd

**Comment by sbromberger** [comment]
Thanks. I'll give that a try.

**Comment by sbromberger** [comment]
on second glance, I'm not sure what I need to be doing for either of those options :) Can you point me in the right direction?

**Comment by folke** [comment]
I just pushed a bunch of changes to Trouble for the `vim.diagnostic` API. This should be working as expected now.
