### ISSUE TITLE
`tidy` broke after `vale` fix (`Ensure linter receives all content before closing stdin` commit)

### ISSUE THREAD

**Issue by cpkio** [mfussenegger/nvim-lint#131]
For some reason `tidy` (on Windows) didn't like the fix you've done for `vale`. I had to revert to
```
    stdin:write('\n', function()
      stdin:shutdown()
      stdin:close()
    end)
```
and set `ignore_exitcode = true` to get rid of `tidy` annoying me with 'exited with code 2' error.

**Comment by mfussenegger** [comment]
Could you check if this still works after https://github.com/mfussenegger/nvim-lint/pull/145 ?
