### ISSUE TITLE
[Question] How to show error code?

### ISSUE THREAD

**Issue by juligreen** [mfussenegger/nvim-lint#138]
With ale I was able to configure my messages to show the flake8 error code (e.g. E501) like this: `let g:ale_echo_msg_format = '[%linter%] %code%: %s [%severity%]'`

How can I do the same with nvim-lint?

**Comment by mfussenegger** [comment]
See `:help vim.diagnostic.config()` and look for the `format` function.

nvim-lint puts the code under `user_data.lsp.code`, of the `diagnostic-structure`, same as LSP clients would do.

**Comment by juligreen** [comment]
Thanks!
After some trial and error this does what I want:
```lua
vim.diagnostic.config({
virtual_text = {
    source = "always",
    format = function(diagnostic)
    if diagnostic.user_data.lsp.code ~= nil then
        return string.format("%s: %s", diagnostic.user_data.lsp.code, diagnostic.message)
    end
    return diagnostic.message
end,
},
})
``
