### ISSUE TITLE
Doesn't work with compound filetypes.

### ISSUE THREAD

**Issue by fullstopslash** [mfussenegger/nvim-lint#141]
I have a really niche use case here. Both Vim and Neovim have a handy feature that allows a file to be recognized as multiple filetypes, then various scripts and autogroup actions can be ran for each of the filetypes that applies. As an example I'm using the [Vimwiki](https://github.com/vimwiki/vimwiki) plugin to edit markdown files, some types of markdown can also be considered a pandoc file as well.  In neovim if I open a markdown file and issue the command `:set filetype` it shows the current filetype as `vimwiki.markdown.pandoc` as expected. However, this plugin doesn't recognize this as a list of filetypes. Instead, as far as I can tell, it recognizes a single filetype `vimwiki.markdown.pandoc` and doesn't load until I issue the command `set filetype=markdown`. At any rate, thanks again for this rad plugin!

**Comment by mfussenegger** [comment]
It is possible to use the full compound fileype like this:


```lua
require('lint').linters_by_ft = {
  ['vimwiki.markdown.pandoc'] = {'vale',}
}
```

Is that sufficient for your use case?

**Comment by fullstopslash** [comment]
Not entirely, as sometimes files that are markdown will change their compound filetypes based on weather or not I'm using the vimwiki plugin. Also, I think there's another issue unrelated to this one as it seems nvim-lint only lints a file that's been passed as a commandline argument to nvim, and not a file that's been opened in a new buffer.

**Comment by mfussenegger** [comment]
You can add multiple entries for that, no?

```
require('lint').linters_by_ft = {
  ['vimwiki.markdown.pandoc'] = {'vale',}
  ['markdown.pandoc'] = {'vale',}
  ['markdown'] = {'vale',}
}
```


It would be possible to change nvim-lint to treat compound filetypes special and split them into each ft + merge and de-duplicate the linters, but not sure if this is common enough to warrant it.

**Comment by fullstopslash** [comment]
Both [Tagbar](https://github.com/preservim/tagbar) and [Vista.vim](https://github.com/liuchengxu/vista.vim) use this method. [Aerial.nvim](https://github.com/stevearc/aerial.nvim/issues/33) has a similar implementation as well.
