### ISSUE TITLE
Sends extra blank line to stdin-reading linters

### ISSUE THREAD

**Issue by dimbleby** [mfussenegger/nvim-lint#144]
For some linters, a trailing blank line is a problem.  But nvim-lint always sends a trailing blank line to stdin-reading linters.

For instance, I am using black via flake8-black via flake8 (for formatting python code).  On a well-formatted file I get the warnings 'blank line at end of file' and 'Black would make changes' - neither of which is true.

Is the fix as simple as: don't insert the extra newline [here](https://github.com/mfussenegger/nvim-lint/blob/b795aa7ba18acd902af47a4394607875c95733ac/lua/lint.lua#L171)?

I think that solves the immediate problem: but even then nvim-lint will always present a newline at the end of the file, which might not actually be present.  Some linters perhaps would like to warn about files that don't end in a newline, which they can never do because all lines that nvim-lint sends do have a newline appended.  But that seems less important.

**Comment by dimbleby** [comment]
I've just spotted that the unwanted trailing line was introduced at https://github.com/mfussenegger/nvim-lint/commit/d6a76b326b82625219b52b62c3b6d47a1fd4b319 to fix #131, so perhaps it's not so straighforward.

**Comment by mfussenegger** [comment]
Can you try with https://github.com/mfussenegger/nvim-lint/pull/145?

**Comment by dimbleby** [comment]
This works fine for me - but isn't it what we had before https://github.com/mfussenegger/nvim-lint/commit/7fb6ae1fb8a6c703b813b138d8d6bb2d7611eb66#diff-236543a3ea3a1d60e5964efd7ceae47669e17cf1ea1215a06765a6ec9a3200cd?  Will this reopen #127?

**Comment by dimbleby** [comment]
Maybe something like this:
```diff
diff --git a/lua/lint.lua b/lua/lint.lua
index fee3ac7..4918463 100644
--- a/lua/lint.lua
+++ b/lua/lint.lua
@@ -165,10 +165,8 @@ function M.lint(linter)
   start_read(linter.stream, stdout, stderr, bufnr, parser, ns)
   if linter.stdin then
     local lines = vim.api.nvim_buf_get_lines(0, 0, -1, true)
-    for _, line in ipairs(lines) do
-      stdin:write(line .. '\n')
-    end
-    stdin:write('\n', function()
+    local content = table.concat(lines, '\n')
+    stdin:write(content .. '\n', function()
       stdin:shutdown(function()
         stdin:close()
       end)
```

I couldn't find a way of getting the actual content of the buffer rather than this line-by-line reconstruction, which seems to me unsatisfactory - eg what if the linter wants to warn you that you have mixed line endings?  But perhaps this will do.

**Comment by mfussenegger** [comment]
> This works fine for me - but isn't it what we had before [7fb6ae1](https://github.com/mfussenegger/nvim-lint/commit/7fb6ae1fb8a6c703b813b138d8d6bb2d7611eb66)? Will this reopen #127?

It's similar yes, but with the new PR the shutdown also uses the callback before invoking close.

> Maybe something like this:

This also sends a trailing `\n` ? Not sure why it would be better than the status quo?

**Comment by dimbleby** [comment]
my version sent only a single trailing newline - which should be present in every posix-compliant file.

However if I'd misread your proposal and it's not going to re-break #127, it's all good - thanks!
