### ISSUE TITLE
Error on try_lint()

### ISSUE THREAD

**Issue by SimonMandlik** [mfussenegger/nvim-lint#147]
I encountered this error when trying to set up `cpplint`:

Packer setup used:

```lua
use { 'mfussenegger/nvim-lint',
  run = 'pip3 install cpplint --upgrade',
  config = function()
      require('lint').linters_by_ft = {
        cpp = {'cpplint',}
      }
  end
}
```

Running `:lua require('lint').try_lint()` gives me this error:

```
E5108: Error executing lua vim/shared.lua:187: t: expected table, got string
stack traceback:
        [C]: in function 'error'
        vim/shared.lua:608: in function 'validate'
        vim/shared.lua:187: in function 'tbl_map'
        ...share/nvim/site/pack/packer/start/nvim-lint/lua/lint.lua:91: in function 'try_lint'
        [string ":lua"]:1: in main chunk
```

`cpplint` by itself works.

**Comment by mflova** [comment]
I recently added it and in my laptop is working fine without any issues. However, I am not using packer since I recently migrated to Neovim and I am still learning about lua or the differences between vim and neovim. I will try to check what's wrong!

**Comment by mflova** [comment]
@SimonMandlik I have been trying to replicate the issue but I could not. It is hard to fix something without being able to replicate it...  :/

**Comment by SimonMandlik** [comment]
Now I can't reproduce it either.. weird. Maybe I uninstalled/updated some incompatible plugin or changed some settings. Nevertheless, linting works flawlessly now :)

Sorry, I will reopen if I bump into it again.
