### ISSUE TITLE
Help setting up LanguageTool

### ISSUE THREAD

**Issue by mflova** [mfussenegger/nvim-lint#163]
I have been trying to set this linter up. From `languagetool.lua` I could see that the executed command that should retrieve the corrections is `languagetool --json --stdin`. However, in my case, the `languagetool`executable I found always opens a separate window with a graphic interface. (And actually this is what happens when I activate this linter through `nvim-lint` and execute the `try_lint` command)
Where can I get the languagetool version used to implement this neovim integrated version?

**Comment by mfussenegger** [comment]
I also can't get it to work anymore. I think I'll just remove - no idea how you're supposed to call it without starting the GUI.

**Comment by pca006132** [comment]
I think the command changed to `languagetool-commandline`?

**Comment by mfussenegger** [comment]
If they did I'd be happy to merge a PR that updates the linter definition

**Comment by mfussenegger** [comment]
Got a PR here that fixed some stuff - so I assume it is working now: https://github.com/mfussenegger/nvim-lint/pull/396
