### ISSUE TITLE
Source as a top-level option

### ISSUE THREAD

**Issue by AckslD** [mfussenegger/nvim-lint#170]
Would it be possible to have the source as a top-level option to the linter rather than to be part of the `parser` function?

In this way it would be easier to reuse an existing linter configuration, for example as:

```lua
lint = require('lint')
lint.linters.mylinter = copy_tbl(lint.linters.mypy)
lint.linters.mylinter.source = 'mylinter'
```

**Comment by mfussenegger** [comment]
Can you elaborate why you would like to customize the source names?

**Comment by seanbreckenridge** [comment]
I do something similar, with a wrapper script for `flake8`, ([`flake8c`](https://github.com/seanbreckenridge/dotfiles/blob/master/.local/share/shortcuts/flake8c)), using a global config file to override any project settings I'm not accustomed to

**Comment by zapling** [comment]
> Can you elaborate why you would like to customize the source names?

I'd like to be able to easily fetch all the diagnostic sources attached by `nvim-lit` and call `vim.diagnostic.reset()` if some condition is fulfilled. Adding a prefix to the name in my case would help me separate sources from e.g lsp.

**Comment by mfussenegger** [comment]
This seems rather an edge case, I may change my mind around this but currently I have no plans to support this.
