### ISSUE TITLE
Linter for multiple/all filetypes

### ISSUE THREAD

**Issue by AckslD** [mfussenegger/nvim-lint#171]
Can I configure a linter, such as `codespell`, for all filetypes? Or maybe all with some exceptions?

**Comment by mfussenegger** [comment]
You could create a custom setup function that sets up the `try_lint` call dynamically.

For example:

```lua
function M.my_lint_setup()
  local lint = require('lint')
  local linters = lint.linters_by_ft[vim.bo.filetype]
  local bufnr = vim.api.nvim_get_current_buf()
  if not linters or vim.tbl_isempty(linters) then
    vim.cmd(string.format(
      "au BufWritePost,BufEnter,BufLeave <buffer=%d> lua require'lint'.try_lint({'codespell'})", bufnr))
    return
  else
    vim.cmd(string.format("au BufWritePost,BufEnter,BufLeave <buffer=%d> lua require'lint'.try_lint()", bufnr))
  end
end
```

You'd have to call this within your `init.vim` or `init.lua`.
If `linters_by_ft` contains an entry for the current filetype it will use these, otherwise it will setup the codespell linter.

You could customize this further as you want. Another example would be to extend `linters_by_ft` dynamically. E.g.


```lua
  local linters = lint.linters_by_ft[vim.bo.filetype]
  if not linters then
    linters = {}
    lint.linters_by_ft[vim.bo.filetype] = linters
    end
  if not vim.tbl_contains(linters, 'codespell') then
    table.insert(linters, 'codespell')
  end
  vim.cmd(string.format("au BufWritePost,BufEnter,BufLeave <buffer=%d> lua require'lint'.try_lint()", bufnr))
```

**Comment by AckslD** [comment]
Thanks @mfussenegger, this gave me ideas on how to do this :)

What I did in the end was just to add two autocmds, one for the normal `try_lint` to trigger the filetype specific linters I configured and another for the global things:
```lua
local lint = require('lint')
lint.linters_by_ft = {
    ...
}

vim.cmd('autocmd BufEnter,BufWritePost,InsertLeave * lua require("lint").try_lint()')
vim.cmd('autocmd BufEnter,BufWritePost,InsertLeave * lua require("lint").try_lint({"codespell"})')
```
