### ISSUE TITLE
Allow to set the CWD on the linter

### ISSUE THREAD

**Issue by sileht** [mfussenegger/nvim-lint#178]
Currently, nvim-lint sets CWD of the linter with the CWD of vim itself. But some linters (like mypy) work well only when launched from the project root directory.

So if `lcd` is used to go somewhere, mypy may not find the project configuration and/or some modules.

I have no idea what the perfect default is `vim.fn.getcwd()` or the project root directory, it really depends on the project and the tool I guess.

But I think the CWD of the linter should be configurable (I play using `lcd` just before launching the linter, but it's a bit hackish).

So if you also think it's a good idea to make CWD configurable, I will be happy to propose a Pull Request.

I imagined to allow something like:
```
require("lint.linters.mypy").cwd = "my path"
```

**Comment by aquillano** [comment]
@mfussenegger Any thoughts?

**Comment by mfussenegger** [comment]
> @mfussenegger Any thoughts?

Thanks for the reminder. See https://github.com/mfussenegger/nvim-lint/pull/179#issuecomment-1225956334
