### ISSUE TITLE
`on_done` not being called

### ISSUE THREAD

**Issue by aoswalt** [mfussenegger/nvim-lint#185]
When adding support for Elixir's [credo](https://hexdocs.pm/credo/overview.html), the `parser` function is not being called.

```lua
require('lint').linters.credo = {
  cmd = 'mix',
  stdin = true,
  args = { 'credo', 'suggest', '--format', 'json', '--read-from-stdin' },
  stream = 'stdout',
  ignore_exitcode = true, -- exits with severity code
  parser = function(output)
    error(vim.inspect(output)) -- never getting here
  end
  }
  ```
  
It looks like `parser.on_chunk` inside of the generated function from `read_output` is being called with the full content, but `parser.on_done` is never being called, so no diagnostics are being generated even though all of the output is provided.

In the luv does, I noticed that it [explicitly mentions](https://github.com/luvit/luv/blob/master/docs.md#uvread_startstream-callback) `EOF`.

> When we've reached EOF, data will be nil.

My assumption is that credo is not outputting an explicit EOF, so luv never calls the callback a final time.

I am not very familiar with luv, and if my assumption is correct, maybe there is a way to perform a final call inside of the `on_exit` callback of `uv.spawn`?

Thank you!

**Comment by nifoc** [comment]
I think I'm running into the same issue. I tried adding `deadnix` as an option, but I only sometimes get results.
The `parser` function is not always being called, even though `deadnix` writes issues to `stdout` (tested with some good old `print` debugging).
