### ISSUE TITLE
Incorrect underlining (byte-based instead of glyph-based)

### ISSUE THREAD

**Issue by cpkio** [mfussenegger/nvim-lint#186]
It seems underlining is byte-wise, not character-wise, which results in erroneous underlines.

### Vale JSON content
```
    {
      "Action": {
        "Name": "replace",
        "Params": null
      },
      "Check": "lexic.CheckBox",
      "Description": "",
      "Line": 336,
      "Link": "",
      "Message": "Использовать 'check box' вместо 'checkbox'",
      "Severity": "error",
      "Span": [
        7,
        14
      ],
      "Match": "checkbox"
    }
```

### Result
![2022-02-14_113207](https://user-images.githubusercontent.com/1917113/153828016-b9bdde00-0c4b-4f15-9ae9-1cf99f3a7233.png)

### Expected
Should underline the `checkbox` text.

**Comment by cpkio** [comment]
This has been discussed here https://github.com/neovim/neovim/issues/17401

As far as I see, it will be `vale` to output byte-based offsets, or `nvim-lint` will have to recalculate diagnostics position: take the line form linter output, find the matched text (returned in JSON in `Match` field) per-byte, and push real byte-values to `vim.diagnostic`.

**Comment by mfussenegger** [comment]
Merged https://github.com/mfussenegger/nvim-lint/pull/187
