### ISSUE TITLE
README: Recommend triggering try_lint only if buffer is modified

### ISSUE THREAD

**Issue by rht** [mfussenegger/nvim-lint#188]
The current readme recommends.
```vim
au BufWritePost <buffer> lua require('lint').try_lint()
```
This is costly, e.g. for 2500 LOC of python, running flake8 causes my CPU consumption to spike from ~7% to ~14%.

I'm trying to migrate from Neomake. With Neomake, by default, the make is not executed if the buffer is not changed.

I think it should be instead
```vim
au BufWritePre <buffer> lua if vim.api.nvim_buf_get_option(0, "modified") then require('lint').try_lint() end
```

**Comment by mfussenegger** [comment]
Your suggested example wouldn't work for linters which read the file from disk because `BufWritePre` triggers before the changes are written to the file.

The readme also just gives a recommendation, anyone is free to use a different way to trigger the linter. I am not going to change it.
