### ISSUE TITLE
Pylint throws an error in some cases

### ISSUE THREAD

**Issue by askfiy** [mfussenegger/nvim-lint#190]
Use nvim test.py to create a py file that nvim-lint throws an exception when editing.

But if nvim opens an existing py file, nvim-lint will not throw an exception.

![Peek 2022-02-24 00-40](https://user-images.githubusercontent.com/81478335/155364999-1496e7d7-afa7-4530-936f-6c0c970bdc40.gif)

my config:

```
require("lint").linters_by_ft = {
    python = {"pylint"}
    -- javascript = {"eslint"},
    -- typescript = {"eslint"},
    -- go = {"golangcilint"}
}

require("lint.linters.pylint").args = {
    "-f",
    "json",
    "--rcfile=~/.config/nvim/lint/pylint.conf"
}


vim.cmd([[
au BufEnter * lua require('lint').try_lint()
au BufWritePost * lua require('lint').try_lint()
]])
```

**Comment by mfussenegger** [comment]
Should be fixed with https://github.com/mfussenegger/nvim-lint/pull/191

Adding the error message as text in the issue would've made it easier to read :)
