### ISSUE TITLE
[Question] How to make ir work?

### ISSUE THREAD

**Issue by ofrades** [mfussenegger/nvim-lint#2]
This is very exciting, thank you for the effort. Does it already work? If so, how can I setup it up?

**Comment by mfussenegger** [comment]
It's not really ready for use yet. Not sure when I get to work on it again - probably sometime within the next one or two weeks. Then I should be able to get it into a state where it can be used.

**Comment by mfussenegger** [comment]
Added basic usage instructions with https://github.com/mfussenegger/nvim-lint/commit/0b99d4d048bb9f3b07e2a83e10ccf3711102167e  and it kinda works now, but there's only two linters for now.
