### ISSUE TITLE
golangci-lint not returning any results

### ISSUE THREAD

**Issue by keyboard-clacker** [mfussenegger/nvim-lint#203]
Hey there! Not sure if this is the right place to put this bug, but I'm trying to use nvim-lint as my linter in go, and I'm having trouble setting args to pass to golangci-lint. Here's my config:

```lua
use({
	"mfussenegger/nvim-lint",
	config = function()
		require("lint").linters_by_ft = {
			go = { "golangcilint" },
		}

		local golangcilint = require("lint.linters.golangcilint")
		golangcilint.append_fname = true
		golangcilint.args = {
			"run",
			"--out-format",
			"json",
			"--config",
			"~/workspace/someDir/.golangci.yml",
			"--timeout",
			"5m",
		}
	end,
})
```

does anything look particularly off here? When I run the command that this _should_ run, aka: `golangci-lint run --out-format json --config ~/workspace/someDir/.golangci.yml --timeout 5m`, it properly outputs a bunch of errors, but I see no output or errors in nvim. I don't even see any errors or anything in my diagnostics when removing those args or any more specific config 

Thanks in advance! I really hope to be able to get this up and running and integrated with nvim native lsp

Cheers,
Kyle

**Comment by mfussenegger** [comment]
Did you setup a autocmd to trigger `try_lint` or tried to invoke it manually?


This is what the readme recomments:

```vimL
au BufWritePost <buffer> lua require('lint').try_lint()
```

**Comment by keyboard-clacker** [comment]
Yeah @mfussenegger

**Comment by mfussenegger** [comment]
Maybe your configuration is not picked up. The `~` in `"~/workspace/someDir/.golangci.yml",` is not automatically expanded. You need to wrap it in a vim.fn.expand call or pass in the absolute path.

**Comment by keyboard-clacker** [comment]
@mfussenegger is that relevant even though when calling golangci-lint binary directly, I can pass relatively paths like that? And my configuration is most definitely not getting picked up, that's the whole problem haha.

**Comment by keyboard-clacker** [comment]
@mfussenegger I see, no I still don't see any document diagnostics or visual indication that anything works when expanding that path either. And when logging out the opts to the linter I see it's passing the expanded path

**Comment by keyboard-clacker** [comment]
Also for what it's worth, I put a log in `nvim-lint/lua/lint/parser.lua`'s `accumulate_chunks` method, the `on_chunk` call, and it appears that that isn't even getting hit. I think something is borked about reading from the output or something with golangcilint

**Comment by mfussenegger** [comment]
Could be related to https://github.com/mfussenegger/nvim-lint/pull/207

**Comment by keyboard-clacker** [comment]
I'll try checking out that branch and seeing if it helps. Also might be relevant, I ran the linter and just got this message as well: 
```
Error executing vim.schedule lua callback: ...packer/start/nvim-lint/lua/lint/linters/golangcilint.lua:24: Expected value but found invalid token at character 1
stack traceback:
        [C]: in function 'decode'
        ...packer/start/nvim-lint/lua/lint/linters/golangcilint.lua:24: in function 'parse'
        ...vim/site/pack/packer/start/nvim-lint/lua/lint/parser.lua:111: in function <...vim/site/pack/packer/start/nvim-lint/lua/lint/parser.lua:109>
```

**Comment by keyboard-clacker** [comment]
I was logging the output before it was trying to decode and this is the output that hit the parser:

```
level=error msg="Parallel golangci-lint is running"
```

**Comment by mfussenegger** [comment]
Based on the comment in https://github.com/mfussenegger/nvim-lint/pull/208 I assume this is solved(?)

**Comment by keyboard-clacker** [comment]
Yep all good! This is fixed now
