### ISSUE TITLE
Feature Request: Support for eslint_d

### ISSUE THREAD

**Issue by yzia2000** [mfussenegger/nvim-lint#206]
eslint_d is much faster than eslint. Wondering if we could add support for it as well. The parsers should be compatible with eslint.

https://github.com/mantoni/eslint_d.js/

**Comment by mfussenegger** [comment]
If the parsers are compatible it may be enough to extend the check here:

https://github.com/mfussenegger/nvim-lint/blob/d754a5f062ca62bc8c3e7ecee7d514ba1dfc4b23/lua/lint/linters/eslint.lua#L11-L16

to see if eslint_d is available and use it instead.

I don't use eslinst/eslint_d so someone else has to do it & test it.

**Comment by SanchayanMaity** [comment]
@mfussenegger Would creating a separate `eslint_d` be ok? Using the system `eslint_d` would also be helpful. Have verified that works.
