### ISSUE TITLE
When running the Vale linter without a configuration value, NeoVim errors when parsing the JSON

### ISSUE THREAD

**Issue by YorickPeterse** [mfussenegger/nvim-lint#21]
This is actually true for any linter that uses NeoVim's `json_decode` function: when the `output` argument is an empty string, this function throws an error. This can happen when a linter is running, but errors. For example, the Vale linter errors when its configuration file is missing.

Perhaps a simple wrapper function is needed that just returns an empty table if the input string is empty?

**Comment by YorickPeterse** [comment]
Sadly we can't depend on the exit code, as many linters produce a status of `1` when diagnostics are produced, while producing the same status code when an internal error/crash is encountered.

**Comment by mfussenegger** [comment]
> For example, the Vale linter errors when its configuration file is missing.

Shouldn't a user notice this, rather than silently not reporting any errors?

If a linter has a json output, doesn't error and produces an empty output instead of an empty array or empty object I'd almost consider that to be a bug with the linter.

**Comment by YorickPeterse** [comment]
@mfussenegger 

> Shouldn't a user notice this, rather than silently not reporting any errors?

The problem is that currently an error in the linter triggers an error in the JSON parsing code, because the output will be an empty string. In case of Vale it does use a different exit code I believe, but this may not be true for all linters. The resulting error is something along the lines of:

```
Error executing vim.schedule lua callback: ...yorickpeterse/Projects/vim/nvim-lint/lua/lint/parser.lua:46: Vim:E474: Attempt to decode
 a blank string
```

That's not very useful to the user :smile: 

So yes, if a linter fails to run ideally that information is presented. But for that to work the `parser` function has to handle missing output.
