### ISSUE TITLE
Error running codespell: EMFILE: too many open files

### ISSUE THREAD

**Issue by AckslD** [mfussenegger/nvim-lint#215]
I sometimes get the following error:
```
...share/nvim/site/pack/packer/start/nvim-lint/lua/lint.lua:181: Error running codespell: EMFILE: too many open files
```
(also for eg `flake8`, `mypy` etc).

Does anyone know the cause of this? I don't have that many files open.

**Comment by mfussenegger** [comment]
Sounds as if file/process handles are not closed.

I added https://github.com/mfussenegger/nvim-lint/commit/0407c340a77380e4122dc349efa10fc846c928b4 to ensure the error case is properly cleaned up, but I suspect you weren't running into that?

Did this start recently - more specifically after https://github.com/mfussenegger/nvim-lint/commit/d754a5f062ca62bc8c3e7ecee7d514ba1dfc4b23 was merged?

**Comment by AckslD** [comment]
Thanks for your reply @mfussenegger!

It started relatively recently, could be since d75a5f but not certain.

I trigger
```lua
require('lint').try_lint()
require('lint').try_lint({"codespell"})
````
on `BufEnter` and `BufWritePost`. I do have a habit of saving quite a lot but not sure that's the issue.

**Comment by AckslD** [comment]
Hi @mfussenegger, I haven't had time to try to revert the commit yet, but let you know once I do and if it helps.

My neovim version is:
NVIM v0.8.0-dev+227-g6613f58ceb

and luv version:
76544

**Comment by dbarrosop** [comment]
I am also having this problem with the golangci-lint linter, I just updated neovim so I will wait and see if it happens again and if it does I will revert https://github.com/mfussenegger/nvim-lint/commit/d754a5f062ca62bc8c3e7ecee7d514ba1dfc4b23 and test.

**Comment by AckslD** [comment]
I'm starting to suspect that it's a combination of plugins starting jobs/threads. I got the same error with one of my own plugins which uses `vim.fn.jobstart`. Does any of you know if there is a way to check how many or what jobs/threads are opened/started with `vim.fn.jobstart` and/or `vim.loop`?

**Comment by mfussenegger** [comment]
By checking the contents of `/proc/<nvim-pid>/fd` it is visible that nvim-lint leaks descriptors with the change made in https://github.com/mfussenegger/nvim-lint/commit/d754a5f062ca62bc8c3e7ecee7d514ba1dfc4b23

Opened a PR that would fix it (https://github.com/mfussenegger/nvim-lint/pull/218) , but I can't verify if it would re-introduce the issue that was originally fixed with that change.

**Comment by AckslD** [comment]
Thanks a lot @mfussenegger, from what I can see this indeed fixes the issue. I tried [this snippet](https://gist.github.com/ii14/b7f77001e1416fef726b5e822c549a17) from @ii14 before and after this change. Before the change I could see a bunch of open handles but not anymore :+1:

**Comment by KevinNitroG** [comment]
idk why but I'm still getting this issue...
