### ISSUE TITLE
How to debug try_lint() not triggering on BufWritePost event?

### ISSUE THREAD

**Issue by aquillano** [mfussenegger/nvim-lint#217]
I've added `au BufWritePost <buffer> lua require('lint').try_lint()` to my init.vim confg like your README suggests. It doesn't seem to be triggering. Running the command `:lua require('lint').try_lint()` does work. How can I debug why the autocommand isn't working?

**Comment by mfussenegger** [comment]
If you use `au BufWritePost <buffer> ` it creates a buffer-local autocommand and it will only trigger in the buffer where you executed `au ..`. You either need to run `au BufWritePost` in each buffer where you want to run `try_lint` or you need to remove the `<buffer>` part.

**Comment by mfussenegger** [comment]
I assume this is solved(?)
