### ISSUE TITLE
Conditionally enable linters

### ISSUE THREAD

**Issue by YorickPeterse** [mfussenegger/nvim-lint#22]
Some linters are very verbose by default, unless you specify a custom configuration file of sorts. For example, https://github.com/jorisroovers/gitlint is such a linter. When using ALE I would disable such linters by default, and only enable them when a configuration file is found. For example:

```vim
" Only enable gitlint if there is a .gitlint config file, as by default gitlint
" is a bit too pedantic.
let config = findfile('.gitlint', expand('%:p:h') . ';')

if empty(config)
  let b:ale_linters = []
else
  let b:ale_linters = ['gitlint']
  let b:ale_gitcommit_gitlint_options = '-C ' . fnamemodify(config, ':p')
end
```

This takes advantage of ALE's buffer-local settings.

While I think using buffer local settings for everything is a bad idea (it gets messy quickly), I'm wondering what the best way of handling this would be. One option would be to add some sort of `run_if` hook that returns `true` by default. Users would then have to somehow override it. For example, using something like this:

```lua
local linters = require('lint').linters

linters.gitlint.run_if = function(bufnr)
  if vim.fn.findfile('.gitlint', vim.fn.expand('%:p:h') .. ';') then
    return true
  else
    return false
  end
end
```

This is just an idea though, and there may be better ways of approaching this.

**Comment by mfussenegger** [comment]
You could setup the autocmd that triggers `try_lint` conditionally on whether this config file exists or not.


For example, I've something like this triggered on `FileType`:


```lua
function M.enable_lint()
  if not require('lint').linters_by_ft[vim.bo.filetype] then
    return
  end
  local bufnr = api.nvim_get_current_buf()
  vim.cmd(string.format("augroup lint_%d", bufnr))
  vim.cmd("au!")
  vim.cmd(string.format("au BufWritePost <buffer=%d> lua require'lint'.try_lint()", bufnr))
  vim.cmd(string.format("au BufEnter <buffer=%d> lua require'lint'.try_lint()", bufnr))
  vim.cmd("augroup end")
  local opts = {
    silent = true;
  }
  api.nvim_buf_set_keymap(bufnr, "n", "]w", "<Cmd>lua vim.lsp.diagnostic.goto_next()<CR>", opts)
  api.nvim_buf_set_keymap(bufnr, "n", "[w", "<Cmd>lua vim.lsp.diagnostic.goto_prev()<CR>", opts)
  api.nvim_buf_set_keymap(bufnr, "n", "<space>", "<Cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>", opts)
end
```


I'm not really sure if it's worth to add a `run_if` predicate to the linters themselves. I feel like this may be something that is quite opinionated and then people end up wanting lots of different options to configure it.

**Comment by YorickPeterse** [comment]
@mfussenegger Maybe a simpler way would be to allow passing linter names to `try_lint()`, then have it only run those linters (if any are given)? That way you wouldn't have to define autocmd groups on the fly, or enable/disable the linter globally on every write.

**Comment by vinicius507** [comment]
I'm using `nvim-lint` with the lint program of my school. I was thinking of a way to disable linting for specific files(like test files or projects outside of school). I didn't manage to do it but it would be a nice feature to have.

**Comment by mfussenegger** [comment]
> Maybe a simpler way would be to allow passing linter names to `try_lint()`, then have it only run those linters (if any are given)? That way you wouldn't have to define autocmd groups on the fly, or enable/disable the linter globally on every write.

Sounds okay but I think I don't fully understand how that would be helpful. How would you use that?
You'll still need to setup some kind of autocmd that then decides which linters to use, no?

**Comment by vinicius507** [comment]
In my case I created a wrapper for the `try_lint()` function.

It is something like this:

```lua
M.lint = function()
    if M.should_lint() then
        -- ...
        require('nvim-lint').try_lint()
    end
end
```

**Comment by mfussenegger** [comment]
So if I understand this right, you'd continue using this pattern, except that `should_lint` would decide which linters to use?

If so - sounds good to me to extend `try_lint` to take an optional `linter_names` argument

**Comment by YorickPeterse** [comment]
Thinking of it: passing the linter names to `try_lint` could be a bit odd. Imagine that for buffer X we have enabled (globally) linters A and B. Using a custom function of sorts we call `try_lint` and pass it linter C, which doesn't support the buffer's file type. What's supposed to happen in this case? Does it simply get ignored, or do we just run the linter and hope for the best?

**Comment by vinicius507** [comment]
> So if I understand this right, you'd continue using this pattern, except that `should_lint` would decide which linters to use?
> 
> If so - sounds good to me to extend `try_lint` to take an optional `linter_names` argument

`should_lint` verifies if the current file is one that we want to be linted. This way you can control the linting process in any way  you want. If you wish to add a feature where the user can disable linting globally and/or per file, it could be verified by `should_lint`.

In my case I did it because my lint configuration can only be used on projects of my school. Projects outside of my school don't need the linting configuration of my school :)

**Comment by YorickPeterse** [comment]
I ended up piecing together a custom linter setup in my dotfiles repository; mostly so I have full control over it and can tweak it to my liking. My setup supports both conditionally enabling linters ([example](https://gitlab.com/yorickpeterse/dotfiles/-/blob/f91e8a0493f6dcafd438b422d2232ce79c493477/dotfiles/.config/nvim/lua/dotfiles/linters/gitlint.lua#L21)) and more dynamic commands/arguments ([example](https://gitlab.com/yorickpeterse/dotfiles/-/blob/f91e8a0493f6dcafd438b422d2232ce79c493477/dotfiles/.config/nvim/lua/dotfiles/linters/rubocop.lua#L39)). Feel free to steal some of these ideas if they're useful :smile:

**Comment by mfussenegger** [comment]
https://github.com/mfussenegger/nvim-lint/pull/26 adds support for passing the linter names directly to `try_lint`. (Main motivation was to be able to try out a linter without having to change the configuration file, but might be useful in the context of this issue here as well)

**Comment by mfussenegger** [comment]
Closing this for now as I don't have a concrete plan how to improve this and I think the current options are good enough.

If there are further concrete suggestions how the APIs could be improved I'm open for suggestions .

**Comment by AckslD** [comment]
@mfussenegger I think having eg an optional `run_if` callback would make a lot of sense. Lets say you have multiple linters for a given filetype but only want some of them to run based on come condition. Setting up autocommands which trigger `try_lint` with then linter name based on some condition seems a lot more cumbersome than being able to define a condition for the linter to be used as a single function.

Although maybe I'm not fully understanding how you suggest this to be done at the moment. Lets say that I have `flake8` and `mypy` for python but I only want `mypy` to run if there is a `tox.ini` in the current directory, how would I do that?

Thanks for the amazing plugin :heart:

**Comment by mfussenegger** [comment]
> Although maybe I'm not fully understanding how you suggest this to be done at the moment. Lets say that I have flake8 and mypy for python but I only want mypy to run if there is a tox.ini in the current directory, how would I do that?

I'd probably run a function in `init.lua` that modifies the `linters_by_ft` table depending on whether the file exists or not.
Or if you need to do the check each time you could have your custom `try_lint` function that does that before triggering the `lint.try_lint()` function.

I don't see a big difference in difficulty between such an approach or having a `run_if` predicate on each linter. Given that I assume that it would be hard to come up with good `run_if` defaults, I'd rather not introduce it at this point.

**Comment by ooloth** [comment]
Another vote for a `run_if` / `condition` option (based on the [`condition`](https://github.com/stevearc/conform.nvim?tab=readme-ov-file#options) option in `conform.nvim`).

My use case is wanting my nvim config to include support for lots of linters per language, but only attach linters that are actually installed in a given project (so the linting in my editor matches the project's linting in CI). I use LazyVim, so while it's easy to pass a custom option (to `opts`), it's not easy to wrap  the `try_lint()` call without overriding [LazyVim's existing custom logic](https://www.lazyvim.org/plugins/linting#nvim-lint) around that call. 

As a Python example, with `conform`, I use a helper function that returns `true` if the formatter is installed in the project's virtual environment. It would be convenient to reuse that same helper for linters if a `condition` / `run_if` option could be made available here as well.

> I assume that it would be hard to come up with good run_if defaults

I think defaulting to `condition = true` (or a function that returns `true`) would be totally fine.

**Comment by znd4** [comment]
idk if this is a separate issue, but I'd like to only register [actionlint](https://github.com/rhysd/actionlint) in github actions files without setting up a custom filetype. Is there a way to dynamically register a linter to the current buffer in a `ftplugin` file? (so that I can wrap it in my own conditional)

**Comment by nemmtor** [comment]
I'd also need this feature in order to run linting for typescript files -  `deno` for repos with `deno.json` file and `eslint_d` for other

**Comment by rice-cracker-dev** [comment]
> Another vote for a `run_if` / `condition` option (based on the [`condition`](https://github.com/stevearc/conform.nvim?tab=readme-ov-file#options) option in `conform.nvim`).
> 
> My use case is wanting my nvim config to include support for lots of linters per language, but only attach linters that are actually installed in a given project (so the linting in my editor matches the project's linting in CI). I use LazyVim, so while it's easy to pass a custom option (to `opts`), it's not easy to wrap the `try_lint()` call without overriding [LazyVim's existing custom logic](https://www.lazyvim.org/plugins/linting#nvim-lint) around that call.
> 
> As a Python example, with `conform`, I use a helper function that returns `true` if the formatter is installed in the project's virtual environment. It would be convenient to reuse that same helper for linters if a `condition` / `run_if` option could be made available here as well.
> 
> > I assume that it would be hard to come up with good run_if defaults
> 
> I think defaulting to `condition = true` (or a function that returns `true`) would be totally fine.

I second this.
