### ISSUE TITLE
Add a passed filename processing function

### ISSUE THREAD

**Issue by cpkio** [mfussenegger/nvim-lint#231]
By default, when `stdin = false`, a filename is added to arguments automatically. But for some linters passing a file path as-is (in Windows, in my case) does not work, you need to replace backslash ('\') with front-facing slash ('/'). So, probably we need an option to pass a transformed file path to linter engine, to control what is passed to executed command.

For now I had to stick to `stdin = true` and pass current file path in `args`, but I don't know if this is a good solution when a linter does not support stdin.

**Comment by mfussenegger** [comment]
There is also a `append_fname` option which you can set to `false` and you can use functions within the `args` to generate the filename
