### ISSUE TITLE
Feature Request: Support for HTML templetes linter

### ISSUE THREAD

**Issue by zefr0x** [mfussenegger/nvim-lint#236]
There is a supported HTML linter, but now a days most people use templets to generate HTML, rather then just writing a normal HTML file.

There are one or more HTML templete generator for every server-side language as listed [here](https://en.wikipedia.org/wiki/Template_engine_(web)#Server-side_systems). Personaly I've used [jinja2](https://en.wikipedia.org/wiki/Jinja_(template_engine)) before in python.

> **Note** HTML Tidy (the current supported HTML linter) don't messes up Jinja templates after [this issue](https://github.com/htacg/tidy-html5/issues/310). So it's usable, and it will not show errors, it will just skip Jinja elements without trying to lint them.

**Here are some HTML templete generator  linters I found:** _(They support more then one templete generator)_
- [djLint](https://djlint.com/) (Active project and support more telemplets)
- [djhtml](https://github.com/rtts/djhtml)
- [curlylint](https://www.curlylint.org/)

**Comment by mfussenegger** [comment]
Added curlylint with https://github.com/mfussenegger/nvim-lint/pull/289
