### ISSUE TITLE
Vale linter doesn't map suggestions

### ISSUE THREAD

**Issue by YorickPeterse** [mfussenegger/nvim-lint#24]
The severity "suggestion" is valid for vale, but not mapped in https://github.com/mfussenegger/nvim-lint/blob/master/lua/lint/linters/vale.lua#L7. This results in an assertion failure [here](https://github.com/mfussenegger/nvim-lint/blob/master/lua/lint/linters/vale.lua#L39).

**Comment by ttys3** [comment]
I got `nvim-lint/lua/lint/linters/vale.lua:39: missing mapping for severity suggestion` error too

![image](https://user-images.githubusercontent.com/41882455/126195322-a501862c-f144-4a1e-98fb-2ecffc30cbb1.png)
