### ISSUE TITLE
PHPCS: expected value but found invalid token

### ISSUE THREAD

**Issue by Mte90** [mfussenegger/nvim-lint#242]
As per screenshot
![Screenshot_20220823_170608](https://user-images.githubusercontent.com/403283/186194347-a3492f10-4cbe-4ba7-bb26-f5fd50eb1437.png)

These are my settings
```
require('lint').linters_by_ft = {
  sh = { 'shellcheck' },
  yaml = { 'yamlint' },
  sass = { 'stylelint' },
  scss = { 'stylelint' },
  css = { 'stylelint' },
  php = { 'phpcs' },
  js = { 'eslint' },
}

vim.api.nvim_create_autocmd({ "BufWritePost" }, {
  callback = function()
    require("lint").try_lint()
  end,
})
```

**Comment by Mte90** [comment]
In my case it is because it is an error and not the json output, I was able to get that info with some workarounds.

**Comment by mfussenegger** [comment]
PR welcome. Linters are maintained by the community

**Comment by Mte90** [comment]
I was thinking to fix that, to do a check if output is json and in case use vim.notify.
It is fine for a PR?

**Comment by mfussenegger** [comment]
Sounds okayish. You could also follow the approach taken for sqlfluff: https://github.com/mfussenegger/nvim-lint/pull/244/files

It adds a diagnostic entry in the first line of the buffer with the output of the linter command as message

**Comment by mfussenegger** [comment]
Merged https://github.com/mfussenegger/nvim-lint/pull/245, thanks
