### ISSUE TITLE
Question: project wide lint

### ISSUE THREAD

**Issue by Integralist** [mfussenegger/nvim-lint#243]
My current setup I end up calling `try_lint()` when writing a buffer so the linting is applied to the current buffer.

Is it possible to run the linter(s) against all the files in the project?

**Comment by mfussenegger** [comment]
An option would be to work with `:cdo` or `:argdo`, but other than that there is currently no built-in support for that.

**Comment by Integralist** [comment]
I think that'll work for now 👍
