### ISSUE TITLE
Consider supporting jsonlint

### ISSUE THREAD

**Issue by Diablo-D3** [mfussenegger/nvim-lint#246]
Being able to lint JSON would be helpful. 

Here is the relevant config from null-ls: https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/diagnostics/jsonlint.lua

**Comment by mfussenegger** [comment]
PR is welcome

**Comment by prichrd** [comment]
Hey @mfussenegger, I'll give this a try for Hacktoberfest if you don't mind!
