### ISSUE TITLE
Consider supporting Taplo for TOML linting

### ISSUE THREAD

**Issue by Diablo-D3** [mfussenegger/nvim-lint#247]
https://taplo.tamasfe.dev/

Mason offers it, but I haven't seen any of the alternative Vim linting plugins support it yet (or any other TOML linter, for that matter).

**Comment by mfussenegger** [comment]
Any reason you're not using the LSP functionality of taplo?

**Comment by Diablo-D3** [comment]
Didn't know I could use it straight as an LSP. Guess that solves the problem.
