### ISSUE TITLE
Configure linter by filetype for yaml.ansible

### ISSUE THREAD

**Issue by ZephOne** [mfussenegger/nvim-lint#248]
Hi,

I've got a problem setting up a linter for the filetype yaml.ansible.
I think it's more a lua issue.
I try to do it this way:

```lua
require('lint').linters_by_ft = { -- line 194
  -- My other linters
  yaml.ansible = {'ansible-lint',}, -- line 196
}

vim.api.nvim_create_autocmd({ "BufWritePost" }, {
  callback = function()
    require("lint").try_lint()
  end,
})
```

And I've got this error when running nvim:

```
Error detected while processing /home/me/.config/nvim/init.lua:
E5112: Error while creating lua chunk: /home/me/.config/nvim/init.lua:196: '}' expected (to close '{' at line 194) near '='.
```

I'm pretty sure that the problem is having a variable like `my.var`. So how can I do when the filetype returned by vim command `set filetype?` is `yaml.ansible`?

**Comment by mfussenegger** [comment]
You need to escape the key due to the `.`:

```lua
require('lint').linters_by_ft = { -- line 194
  -- My other linters
  ['yaml.ansible'] = {'ansible-lint',}, -- line 196
}
```

See https://learnxinyminutes.com/docs/lua/ and https://github.com/nanotee/nvim-lua-guide
