### ISSUE TITLE
Error running cargo check: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by Integralist** [mfussenegger/nvim-lint#252]
My configuration looks a bit like this...

```
local lint = require("lint")

lint.linters.cargo = {
  cmd = "cargo check",
  stdin = false,
  args = {},
  stream = "both",
  ignore_exitcode = false,
  env = nil,
}

lint.linters_by_ft = {
  rust = { "cargo" },
}
```

But I'm seeing the following error flash up:

```
Error running cargo check: ENOENT: no such file or directory
```

I'm not sure why that is. I even tried passing the full path to `cargo` and it errors the same.

Does anyone have any ideas?

Thanks.

**Comment by mfussenegger** [comment]
`cargo check` is not a single command. `cargo` is the command and `check` needs to be moved to the `args`

```lua
lint.linters.cargo = {
  cmd = "cargo",
  stdin = false,
  args = {"check"},
  stream = "both",
  ignore_exitcode = false,
  env = nil,
}
```

But you'll also need a `parser` function

**Comment by Integralist** [comment]
That's great, thanks for clarifying!
