### ISSUE TITLE
FR: Command to ignore rule violation at line

### ISSUE THREAD

**Issue by chrisgrieser** [mfussenegger/nvim-lint#258]
Many linters ([one example here](https://stylelint.io/user-guide/ignore-code/)) allow you to disable/ignore a rule at a particular line. it would be very useful if nvim-lint provided a command that automatically adds such an "disable-rule-comment". 

I come from Sublime, and [SublimeLinter has such a feature](https://github.com/SublimeLinter/SublimeLinter/blob/master/keymaps/Default%20(Windows).sublime-keymap#L38), for example.

**Comment by mfussenegger** [comment]
This is kinda out-of-scope for nvim-lint, it will remain a pure linter system. I think [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) would support that.

I think if one wanted to it would be possible to build such a system on-top or separate to nvim-lint. I suspect there wouldn't be a lot of code re-use for the functionality anyways, as it might imply different cmd-line arguments and parse logic.
