### ISSUE TITLE
Bug: eslint does not work

### ISSUE THREAD

**Issue by chrisgrieser** [mfussenegger/nvim-lint#259]
So I have selene, shellcheck, and stylelint installed, all of which work fine with this plugin.

However, it seems it does not work with eslint. 

I also tried manually running `lua require("lint").try_lint()`, but nothing happens, no error message at all.

all linters are also installed at the same location, so it cannot be an issue with PATH, I assume?
<img width="1157" alt="Pasted image 2022-10-10 15 24 24" src="https://user-images.githubusercontent.com/73286100/194876735-121e701e-15cb-4ac5-a52a-6a6d9afc43ad.png">

**Comment by mfussenegger** [comment]
`eslint` tries the local `./node_modules/.bin/eslint` path and if it doesn't exist it will use the global `eslint` that should be in `$PATH`.

Maybe the pattern is wrong in https://github.com/mfussenegger/nvim-lint/blob/master/lua/lint/linters/eslint.lua ?
I don't use eslint myself.

**Comment by SanchayanMaity** [comment]
FWIW, I use `eslint` and it works just fine here. To check whether it actually runs outside of neovim/nvim-lint would help in pinpointing if it is not an error in `eslintrc` or similar.

`eslint <filename>` 

or

`npx eslint <filename>`
