### ISSUE TITLE
Avoid error if linter is not installed

### ISSUE THREAD

**Issue by danrot** [mfussenegger/nvim-lint#272]
I have configured nvim-lint to lint my files as explained in the `README.md`:

```lua
vim.api.nvim_create_autocmd(
	{ 'BufWritePost' },
	{
		callback = function()
			lint.try_lint()
		end
	}
)
```

This works well, but I have one issue: I am using a relative path in my `PATH` variable so that I always have correct version of some linters in the `PATH`. This also works well, but it has a drawback with the above implementation: If I start a small project for which I don't have a linter installed, then I always get an error when saving the file:

```
Error detected while processing BufWritePost Autocommands for "*":
Error running eslint: ENOENT: no such file or directory
```

I quickly tried wrapping the `lint.try_lint` command using `pcall`, but that did not work... Is there anyway of avoiding that error message? I do not really care about it, and it forces me to press an additional enter when I save the file.

**Comment by mfussenegger** [comment]
`pcall` doesn't work because the error is internally already caught and presented to the user via a `notify`:

https://github.com/mfussenegger/nvim-lint/blob/666ed80fcb78cf6355f3d5b7ebdbacef6465578c/lua/lint.lua#L121-L124

Adding an option to ignore errors with: https://github.com/mfussenegger/nvim-lint/pull/273

**Comment by danrot** [comment]
Awesome, that was fast, thank you!

**Comment by danrot** [comment]
Somehow this is not working for me... I've updated my config to look like this:

```lua
vim.api.nvim_create_autocmd(
	{ 'BufWritePost' },
	{
		callback = function()
			lint.try_lint(nil, { ignore_errors = true })
		end
	}
)
```

But somehow it is still showing the same error as before 🤔 Is the call as I've shown it here correct?

**Comment by mfussenegger** [comment]
> that was fast

Turns out - too fast. I missed the case that caused your error message. Should be fixed now with https://github.com/mfussenegger/nvim-lint/pull/275

**Comment by danrot** [comment]
Thank you, now it works!
