### ISSUE TITLE
Feature request: show/hide/toggle

### ISSUE THREAD

**Issue by bobsrentacow** [mfussenegger/nvim-lint#303]
I'd really like to be able to toggle diagnostic display with vim.diagnostic.show/hide or enable/disable.  I have a branch of this I can push if you are open to contributions.  Is there already a mechanism that I ought to use instead of modifying this code?

**Comment by mfussenegger** [comment]
> I'd really like to be able to toggle diagnostic display with vim.diagnostic.show/hide or enable/disabl

This should already work?

**Comment by ridicolos** [comment]
Would be cool if you can deactivate linters on the fly when you are inside a file. For example, I have two different linters active for markdown-files. I would love to be able to deactivate one of them if I am in a project, where I don't need the linter.

**Comment by mfussenegger** [comment]
You can either modify the `linters_by_ft` table at runtime or call `try_lint` with the linter names you want to use

**Comment by ridicolos** [comment]
Can you give an example on how I can run `try_lint` while I am in a current file? 

Because I already have this configured:

```
require('lint').linters_by_ft = {
  markdown = {'markdownlint', 'codespell'}
}
```

I want to remove `codespell` for all my markdown-files in the future. But I want to be able to reactivate this while I am inside a file and need it.
