### ISSUE TITLE
How to configure arguments for linters

### ISSUE THREAD

**Issue by coltonmorris** [mfussenegger/nvim-lint#31]
I'm trying to use revive and need to pass in my config. 
I see that `lua/lint/linters/revive.lua` has an args field, but I don't see how to set it.

Is the intended way to define it as a custom linter?

Thanks for the great lib, very clean and minimal, good work 👍

**Comment by coltonmorris** [comment]
I figured it out, my config looks like this:
```lua
local lint = require'lint'

lint.linters.revive.args = {'-config', 'path/to/config.toml'}

lint.linters_by_ft = {
    go = {'revive'},
}
```
One thing I got hung up on was trying to use an env var to describe the path to the config file, which didn't work. So I had to use an absolute path instead.

**Comment by mfussenegger** [comment]
To be honest I didn't really consider the customization aspect like that. But yes - your solution seems good.
