### ISSUE TITLE
psalm linter is called twice

### ISSUE THREAD

**Issue by ii02735** [mfussenegger/nvim-lint#316]
Hello,

I'm a newbie in neovim, and I'm trying to make an IDE.

I have a neovim lua configuration with LSP installed like this : 

```lua

local lsp = require('lsp-zero')
local configs = require('lspconfig.configs')
local lspconfig = require('lspconfig')
local servers = {
	'tsserver',
	'eslint',
	'intelephense',
	'psalm',
	'html',
	'jsonls',
	'marksman',
	'pyright',
	-- 'gopls' : requires go interpreter to be installed
}

lsp.preset('recommended')

lsp.ensure_installed(servers)

lsp.set_preferences({
	sign_icons = {}
})

lsp.on_attach(function(client, bufnr)
	local opts = {buffer = bufnr, remap = false}
	vim.keymap.set("n", "gd", function() vim.lsp.buf.definition() end, opts)
end)

lsp.setup()

-- Set up lspconfig.
local capabilities = require('cmp_nvim_lsp').default_capabilities()

for _, lsp in ipairs(servers) do
	lspconfig[lsp].setup {
	-- on_attach = my_custom_on_attach,
	capabilities = capabilities,
	}
end
```
I've installed several servers, and I've added the psalm linter for nvim-lint : 

```lua
local lint = require('lint')

-- apply linters by filetype

lint.linters_by_ft = {
    php = { 'psalm' }
}

vim.api.nvim_create_autocmd({ "BufWritePost" }, {
    callback = function()
      lint.try_lint()
    end,
  })
```

The problem is that the psalm linter is invoked twice :

![image](https://user-images.githubusercontent.com/33719388/232863499-5b839b62-7652-40fb-bf8a-b1567019ec1c.png)

It seems that the psalm server is invoked, then the `nvim_create_autocmd` statement is called.
Is there any way to prevent the psalm server from being invoked in favor of the linter ?

**Comment by mfussenegger** [comment]
Remove `psalm` from your `servers` list?

I'm sorry but the issue tracker isn't for general help but for bugs or feature requests.

**Comment by ii02735** [comment]
Hello @mfussenegger ,

Thank you for your reply. I removed psalm for my servers list.
And when I try to save my PHP file, I have this error : 

```
Error detected while processing BufWritePost Autocommands for "*":
Error running psalm: ENOENT: no such file or directory
```

Sorry for the disturbance, I will ask my question somewhere else.

**Comment by mfussenegger** [comment]
That means the `psalm` executable is not in your path and also not in `./vendor/bin/psalm` or `./vendor/bin/psalm.phar`, relative to your current working directory.

**Comment by ii02735** [comment]
@mfussenegger Thank you for your reply.
It wasn't working before because I didn't open my file *from* my root directory.

I was doing this :
```sh
cd src
nvim script.php
```

Instead of that : 
```sh
nvim src/script.php
```

It is now working :+1:
