### ISSUE TITLE
Trouble running linters installed with mason

### ISSUE THREAD

**Issue by yngwi** [mfussenegger/nvim-lint#327]
Hi, I'm having trouble running some (but not all) linters installed with mason.nvim on Windows 11. One example is `vale`. I have installed it with mason, if I run `!which mason`, the path points to the correct executable and it is also executable by running `!vale` or in the internal terminal. However, nvim-lint gives me the following error message when running my autocommand:
```
Error detected while processing BufReadPost Autocommands for "*":
Error running vale: ENOENT: no such file or directory
```
I'm running a nightly from earlier this week and have the latest plugin and linter versions. Any help is appreciated.

**Comment by mfussenegger** [comment]
PRs to add `.cmd` handling for windows to the linters that require it are welcome. I don't use windows myself
