### ISSUE TITLE
Dynamic arguments

### ISSUE THREAD

**Issue by jorrete** [mfussenegger/nvim-lint#337]
Could be args be retrieved dynamically? With html-tidy sometimes I add arguments when is a xml page or when is a chunk of html and not a html page. Maybe if args could be a function which receives buffer and content that returns a table would give more flexibility.
Thanks.

**Comment by mfussenegger** [comment]
A individual argument can be a function or if you need to set additional arguments dynamically you can turn the full linter into a function. 

See the compiler linter for an example:

https://github.com/mfussenegger/nvim-lint/blob/107fa76843fbb0b04870dab1147296a210df568b/lua/lint/linters/compiler.lua#L1-L28
