### ISSUE TITLE
Output is blank?

### ISSUE THREAD

**Issue by 9mm** [mfussenegger/nvim-lint#339]
I have linters installed with Mason. I know the `!xxx` commands work from command line, so I know the commands are in the path.

I don't get any errors about 'path not found' so I'm pretty sure nvim-lint is seeing them. The problem is I'm not actually getting any output. I've tried 2 different ones.

`eslint_id` and the `go` linter. Maybe the problem is trying to run the lint command from a hotkey?

```
return {
  'mfussenegger/nvim-lint',
  config = function()
    local lint = require('lint')
    lint.linters_by_ft = {
      go = { 'golangcilint' },
    }

    vim.keymap.set('n', '<Leader>l', lint.try_lint, { desc = 'Lint' })
  end,
}
```

How do we do things like running `--fix` with eslint_d?

**Comment by DanielAndreasen** [comment]
I had a bit similar problem as you. I changed some args for my linter according to this https://github.com/mfussenegger/nvim-lint#customize-built-in-linter-parameters.
However, I had to **add** my options. My config look like this:
```lua
local lint = require('lint')

local mypy = lint.linters.mypy
mypy.args = {
    '--show-column-numbers',
    '--hide-error-codes',
    '--hide-error-context',
    '--no-color-output',
    '--no-error-summary',
    '--no-pretty',
    '--ignore-missing-imports',
    '--disallow-untyped-defs'
}

lint.linters_by_ft = {
    python = { 'mypy', }
}

vim.api.nvim_create_autocmd({ "BufWritePost" }, {
  callback = function()
    lint.try_lint()
  end,
})
```

Only the last two options are custom, the rest are default. You might have to look at https://github.com/mfussenegger/nvim-lint/blob/master/lua/lint/linters/golangcilint.lua to check how it should be configured.
