### ISSUE TITLE
Lint on TextChanged in insert mode

### ISSUE THREAD

**Issue by tanguymagne** [mfussenegger/nvim-lint#341]
Firstly I would like to thank you for this amazing plugin.

I am quite new to NeoVim, and I am trying to make the linting update on every text change in insert mode (ideally, linting should start every time I stop typing, so for instance with a delay of 100ms). I tried to use the TextChangedI (see [here](https://neovim.io/doc/user/autocmd.html)) but it doesn't seem to be working.

I am using neovim 0.9.1 with NVChad.
My config is as follow
```
├── init.lua
├── lazy-lock.json
├── LICENSE
└── lua
   ├── core <default from NVChad>
   ├── custom
   │  ├── chadrc.lua
   │  ├── configs
   │  │  ├── lint.lua
   │  │  └── lspconfig.lua
   │  └── plugins.lua
   └── plugins <default from NVChad>
```

with `plugins.lua`:
```
local plugins = {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "pyright",
        "ruff",
      },
    },
  },
  {
    "neovim/nvim-lspconfig",
    config = function ()
      require "plugins.configs.lspconfig"
      require "custom.configs.lspconfig"
    end,
  },
  {
    "mfussenegger/nvim-lint",
    lazy=false,
    config = function ()
      require "custom.configs.lint"
    end
  },
}
return plugins
```

and `lint.lua`:
```
require('lint').linters_by_ft = {
  python = {'ruff',}
}

vim.api.nvim_create_autocmd(
  {"BufEnter", "BufWritePost", "InsertLeave", "TextChanged",  "TextChangedI"}, 
  {
    callback = function()
      require('lint').try_lint()
    end,
  }
)
```

Do you know if it's possible to achieve what I want?

Thank you very much for your help

**Comment by mfussenegger** [comment]
This should be working for linters that support stdin. Can you describe the behavior you see vs. what you'd expect in more detail?
