### ISSUE TITLE
FR: vim's `spell` as source?

### ISSUE THREAD

**Issue by chrisgrieser** [mfussenegger/nvim-lint#353]
I don't know how feasible that is, but I was thinking that vim's built-in spellchecker could also be an interesting source. 

By hooking them up to LSP-diagnostics-API, you could unify `next diagnostic` and `next misspelling`, get statusline displays, etc.

**Comment by mfussenegger** [comment]
Adding "internal" linters is not really in scope.
nvim-lint is primarily for external linters. All it does it spawn an executable and parse the output. Creating diagnostics from the spellcheck functionality doesn't need that.

This might be worth creating an upstream issue in neovim to support that out of the box or create a dedicated plugin. I don't really see the benefit of having it here, other than to appease people who think more plugins = more bloat.
