### ISSUE TITLE
Long running linters can accumulate

### ISSUE THREAD

**Issue by TimDeve** [mfussenegger/nvim-lint#357]
It seems there is a bug in the part of codebase that ensures that when a linter is run it sigterms the previous invocation of it, it sometimes does but most of the time it seems to accumulate. 

My gut says that there might be a race around lua/lint.lua:154 and that storing previous linter in a pid - > proc table might avoid it but I've not had the time to validate that.

**Comment by OldWorldOrdr** [comment]
any progress on this? my system has froze multiple times when poking around in autoconf configure scripts

**Comment by TimDeve** [comment]
It seems that `lint` and `try_lint` erase each other's data. [Here](https://github.com/mfussenegger/nvim-lint/compare/master...TimDeve:nvim-lint:sigterm-old-lints)'s a basic diff that fixes it. I've not had the time to figure out why `lint` did that cleanup in the first place though so I've not raised a PR yet.

**Comment by TimDeve** [comment]
#417 has been merged which fixes the issue
