### ISSUE TITLE
Feature Request: Fucntion to retrieve currently attached linter

### ISSUE THREAD

**Issue by mesa123123** [mfussenegger/nvim-lint#361]
I know in the lsp client there is a function that allows me to see what lsp server is attached to the current session, it would be cool to have one that would show the current linter attached to the current client as well:

I want to use this for my lualine config:
![image](https://github.com/mfussenegger/nvim-lint/assets/22901019/710a68ec-5836-47b4-af2a-6c190f3f4b88)

You can see the pyright server there so I'd like it to say "pylint" as well

Is this something you can already do?

**Comment by mfussenegger** [comment]
`linters_by_ft[vim.bo.filetype]`  gives you the linters you've configured for the current filetype.
