### ISSUE TITLE
is it possible to assign linter to all filetypes?

### ISSUE THREAD

**Issue by madelaney** [mfussenegger/nvim-lint#369]
All,

I have the following basic config:
```lua
local lint = require('lint')
lint.linters_by_ft = {
  ruby = {
    'rubocop',
  },
  markdown = {
    'markdownlint',
  },
  groovy = {
    'npm-groovy-lint',
  },
}
```

I'd also like to add `codespell` to all of the above file types but it wasn't clear if that was possible. Is it possible to just add `codespell` to all file types?

**Comment by WhoIsSethDaniel** [comment]
A small bit of code works. After your code above just do
```
for ft, _ in pairs(l.linters_by_ft) do
  table.insert(l.linters_by_ft[ft], 'codespell')
end
```
I don't know if this is what you're looking for, but I do this for a different linter and it works fine.

**Comment by mfussenegger** [comment]
See https://github.com/mfussenegger/nvim-lint/issues/355#issuecomment-1759203127
