### ISSUE TITLE
Get error while running cppcheck 

### ISSUE THREAD

**Issue by Blackwood416** [mfussenegger/nvim-lint#382]
![Screenshot_2023-09-28-13-20-24-489_com gaurav avnc](https://github.com/mfussenegger/nvim-lint/assets/73172752/de1766bf-1553-4022-a0b1-7a70b858c53a)
I got this error message in neovim after running pacman -Syu in my Arch Linux and :Lazy update in my neovim. I don't know how to get neovim's run log so I can just upload this screenshot. I tried to run cppcheck in my shell with parameters in cppcheck.lua and it worked fine. Other linters worked fine, too. Do anyone meet the same problem?

**Comment by alekgajos** [comment]
`cppcheck` failed for me as well. In my case, it was related to the following part of `cppcheck` invocation:

```
--cppcheck-build-dir=build
```
which assumes there is a `build` directory in the location from which cppcheck is called. The latter is not always obvious as your current working directory may be changed by the `autochdir` option or plugins such as `projects.nvim`.

The solution was ensuring to have the `build` directory in neovim's current working directory or overriding the expected build-dir path in args like this:
```
    local cppcheck = require('lint').linters.cppcheck
    cppcheck.args = {
      '--enable=warning,style,performance,information',
      '--language=c++',
      '--inline-suppr',
      '--cppcheck-build-dir=/home/alek/.builds/',
      '--template={file}:{line}:{column}: [{id}] {severity}: {message}'
    }
```

**Comment by Blackwood416** [comment]
> `cppcheck` failed for me as well. In my case, it was related to the following part of `cppcheck` invocation:
> 
> ```
> --cppcheck-build-dir=build
> ```
> 
> which assumes there is a `build` directory in the location from which cppcheck is called. The latter is not always obvious as your current working directory may be changed by the `autochdir` option or plugins such as `projects.nvim`.
> 
> The solution was ensuring to have the `build` directory in neovim's current working directory or overriding the expected build-dir path in args like this:
> 
> ```
>     local cppcheck = require('lint').linters.cppcheck
>     cppcheck.args = {
>       '--enable=warning,style,performance,information',
>       '--language=c++',
>       '--inline-suppr',
>       '--cppcheck-build-dir=/home/alek/.builds/',
>       '--template={file}:{line}:{column}: [{id}] {severity}: {message}'
>     }
> ```

It worked! 👍 Thank you so much!
