### ISSUE TITLE
Utility to extend linter args

### ISSUE THREAD

**Issue by petobens** [mfussenegger/nvim-lint#386]
Currently to add an extra arg to a linter we need to copy current args and then add the extra one (in the following example the `--config` bit): 
```lua
local linters = require('lint').linters
linters.luacheck.args = {
    '--formatter',
    'plain',
    '--codes',
    '--ranges',
    '--config=' .. vim.env.HOME .. '/.config/.luacheckrc',
    '-',
}
```
Is is possible to add an utility function as in https://github.com/stevearc/conform.nvim/commit/aada09c9cfea38187966ce47f34b9008e1104d21 to be able to do something like:
```lua
lint_utils.add_lint_args(
    linters.luacheck,
    { '--config=' .. vim.env.HOME .. '/.config/.luacheckrc' }
)
```
or
```lua
linters.luacheck.extra_args = {
    '--config=' .. vim.env.HOME .. '/.config/.luacheckrc',
}
```
Thanks in advance!

**Comment by mfussenegger** [comment]
Something like this should work:

```lua
vim.list_extend(vim.deepcopy(linters.luacheck.args), {  '--config=' .. vim.env.HOME .. '/.config/.luacheckrc', })
```

I'm not adding additional utils to copy/extend lists.

**Comment by petobens** [comment]
Makes sense. Thanks for the snippet!
