### ISSUE TITLE
cancelling processes with sigterm resets the diagnostics

### ISSUE THREAD

**Issue by emmanueltouzery** [mfussenegger/nvim-lint#388]
the idea of killing existing linter processes when a new concurrent lint is requested is causing the diagnostics to reset for me.

at least in the case of eslint, when we call `proc:kill("sigterm")`, nvim-lint thinks that the eslint that we just killed finished successfully and found that there are no linting errors. Therefore all diagnostics are removed.
A little later, the new-running linter succeeds and now diagnostics are added back.

On my setup, due to the signs column, it makes the code shift left (diagnostics are removed) then back right (they are added back).

I'm not sure whether it would be possible to detect that the linter failed (was killed by sigterm), and that therefore we should not reset the diagnostics, to avoid this issue.

I confirmed that this change fully solves the issue for me:
```diff
  for linter_name, proc in pairs(running_procs) do
-   if not proc:is_closing() then
-     proc:kill("sigterm")
-   end
-   running_procs[linter_name] = nil
+   return
  end
```

So from my point of view, I see two solutions:
1. instead of killing existing running processes, let the existing one finish and don't run the new one (that still solves the problem of having many concurrently running processes) -- this is what my change does
2. somehow detect that the process was killed by nvim-lint and don't reset the diagnostics to empty in that case

**Comment by emmanueltouzery** [comment]
Hmm, the first solution could cause the diagnostics to be out of date. So I guess only the second approach, detecting that the prices was killed by us, would be the right one...

**Comment by emmanueltouzery** [comment]
Ok, i got an idea that would work at least for eslint. So the issue is that many linters, if not all, will return an exit code of 1 already if there are linter errors, so it's hard to distinguish between "exit code 1, it's just the linter finding errors" and "exit code 1, we killed the linter and so we should ignore the results".

However when this happens, my issue is with the situation "exit code 1, and the linter returned no issues at all".

So it would solve my issue if we'd add an if somewhere "if the linter returned a non-zero exit code, but didn't list any errors, ignore this run and assume that happened because we killed it".

We could potentially add some setting in the linter declaring API, whether it's safe to make that assumption (I'd probably set it to on by default -- that it's safe to make the assumption).

What do you think about that? Would you accept a PR to that effect?

**Comment by emmanueltouzery** [comment]
so I started some work on tracking PIDs of processes that get killed and then not publishing the results for these pids later on, but then I realized that sometimes I also lose the signs column unrelated to this (it happens also with null-ls). That makes testing the effect of the fix quite hard, as I'm never sure why I'm losing the sign column.. So right now I'm not sure what to do and whether I correctly identified the issue to begin with.

**Comment by mfussenegger** [comment]
Should be fixed with https://github.com/mfussenegger/nvim-lint/pull/442/commits/e433148f97073d564c7c151d82e0e109093ca15a
