### ISSUE TITLE
eslint_d not working

### ISSUE THREAD

**Issue by nfwyst** [mfussenegger/nvim-lint#391]
I installed eslint_d by mason, and configured      

```js 
javascript = { "eslint_d" },
```

but there is no any lint message after calling try_lint() when editing javascript file.

**Comment by scarletchaos** [comment]
did you fix it? How?

**Comment by nfwyst** [comment]
> did you fix it? How?

this is not a bug, should be configured with eslint config file for eslint_d working

**Comment by ewal** [comment]
A bit late, but if anyone looking for an answer the solution is described in the following comment https://github.com/mantoni/eslint_d.js/issues/21#issuecomment-158789637

Just run `eslint_d restart` from within a (n)vim terminal
