### ISSUE TITLE
Postprocess severities

### ISSUE THREAD

**Issue by petobens** [mfussenegger/nvim-lint#392]
I'm using the ruff linter which treats all diagnostics as warnings. Coming from null-ls I could easily hook into the diagnostics and modify the severity by doing something like:
```lua
local ruff_severities = {
    ['E'] = vim.diagnostic.severity.ERROR,
    ['F8'] = vim.diagnostic.severity.ERROR,
    ['F'] = vim.diagnostic.severity.WARN,
    ['W'] = vim.diagnostic.severity.WARN,
    ['D'] = vim.diagnostic.severity.INFO,
    ['B'] = vim.diagnostic.severity.INFO,
}
local ruff = null_ls_diagnostics.ruff.with({
    diagnostics_postprocess = function(diagnostic)
        local code = string.sub(diagnostic.code, 1, 2)
        if code ~= 'F8' then
            code = string.sub(code, 1, 1)
        end
        local new_severity = ruff_severities[code]
        if new_severity then
            diagnostic.severity = new_severity
        end
    end,
})
```
I guess the way to do this in nvim-lint is to call the `try_lint` function and then capture the diagnostics and post process it with something like:
```lua
local function severity_postprocess(diagnostics)
    for _, v in pairs(diagnostics) do
        if v.source == 'ruff' then
            -- Try to do something with the error code here
            -- v.user_data.lsp.code
        end
    end
end
...
severity_postprocess(vim.diagnostic.get(0))
```
Is this the way? Is there a simpler one? Thanks in advance!

**Comment by mfussenegger** [comment]
You could override/wrap the linters parse function, but the better option would be to create a PR that sets the severities properly in the first place.

**Comment by petobens** [comment]
Following your tip I overrode the parse function https://github.com/petobens/dotfiles/commit/bb693c3bb403a5ad4631f1ba78eee30c590d80bb

Thanks!
