### ISSUE TITLE
Recommended way to run a linter under a virtual environment?

### ISSUE THREAD

**Issue by hahuang65** [mfussenegger/nvim-lint#407]
The idea is, I'd like to check to see if the project has a `Pipfile` or a `poetry.lock` file, and correspondingly run `mypy` with `pipenv run mypy` or `poetry run mypy`, respectively.

Currently, I'm doing something like this:

```
return {
  "mfussenegger/nvim-lint",
  config = function()
    -- Customize linters
    vim.api.nvim_create_autocmd({ "FileType" }, {
      group = "lint",
      pattern = { "python" },
      callback = function()
        local dir = vim.uv.cwd()
        if vim.tbl_contains(mypy_dirs, dir) then
          return
        else
          table.insert(mypy_dirs, dir)
        end

        local mypy = require("lint").linters.mypy
        require("lspconfig").util.search_ancestors(dir, function(path)
          local pipfile = require("lspconfig").util.path.join(path, "Pipfile")
          local poetry_lock = require("lspconfig").util.path.join(path, "poetry.lock")
          if require("lspconfig").util.path.is_file(poetry_lock) then
            vim.notify_once("Running `mypy` with `poetry`")
            mypy.cmd = "poetry"
            mypy.args = vim.list_extend({ "run", "mypy" }, mypy.args)
          elseif require("lspconfig").util.path.is_file(pipfile) then
            vim.notify_once("Running `mypy` with `pipenv`")
            mypy.cmd = "pipenv"
            mypy.args = vim.list_extend({ "run", "mypy" }, mypy.args)
          else
            vim.notify_once("Running `mypy` without a virtualenv")
          end
        end)
      end,
    })
  end,
}
```

This comes with the downside of always running when I open a Python file, as well as, seemingly running twice (once when `nvim-lint` hooks in, and again when the autocommand triggers.

Is there a better way to do this?

**Comment by mfussenegger** [comment]
You could create a custom linter where either the full linter is a function, or the `cmd` and `args` elements are functions.

See https://github.com/mfussenegger/nvim-lint/blob/67f74e630a84ecfa73a82783c487bdedd8cecdc3/lua/lint/linters/eslint.lua#L10-L17

Or https://github.com/mfussenegger/nvim-lint/blob/67f74e630a84ecfa73a82783c487bdedd8cecdc3/lua/lint/linters/perlcritic.lua#L20-L21

For examples where that functionality is used.
