### ISSUE TITLE
Feature Request: Disable Linters manually

### ISSUE THREAD

**Issue by AmmarAbouZor** [mfussenegger/nvim-lint#411]
Thanks for this great plugin it's much faster than any other one with easy configuration.

In my workflow I like to have keybindings to toggle spellcheck manually, and I'm using CSpell linter for that, however I'm still unable to achieve that.

I've searched the issues and found very useful information in #303, which helped me to activate the linter manually but I couldn't find a way to deactivate it. 

Any solution or work-around would be very appreciated

Here is a snippet from my keybindings

```lua
-- Activate CSpell => This works great
vim.keymap.set("n", "<leader>us", function()
  require("lint").try_lint("cspell")
end, { desc = "Activate CSpell" })

-- Deactivate CSpell => This doesn't work
vim.keymap.set("n", "<leader>uq", function()
-- a method like disable_lint would be great here
  require("lint").????("cspell")
end, { desc = "Deactivate CSpell" })
```

**Comment by AmmarAbouZor** [comment]
I've found a work around that's good for me. I can reset the diagnostics for the current buffer 

```lua
vim.keymap.set("n", "<leader>uq", function()
  vim.diagnostic.reset(nil, 0)
end, { desc = "Reset Diagnostic" })
```

This is enough for my use case, and the issue can be closed  :+1:

**Comment by pbnj** [comment]
@AmmarAbouZor - why `vim.diagnostic.reset()` and not `vim.diagnostic.disable()` ?

**Comment by AmmarAbouZor** [comment]
@pbnj Thanks for suggestions and the snippets. I'll keep them because it would be really helpful when I need to setup linters to lint automatically via autocmds.

For my current use-case I don't use any linter besides the `CSpell` and I call the linting only manually, that's why I use `reset()` over `disable()` to remove the current diagnostics but to keep using the LSP diagnostics after that.

**Comment by amirza82** [comment]
I've done this: 
```
vim.keymap.set("n", "<leader>l", function ()
	if vim.diagnostic.is_enabled() then
		vim.diagnostic.enable(false)
	else
		vim.diagnostic.enable(true)
	end
end, { desc = "toggle lint" })
```
 might be useful to someone.
