### ISSUE TITLE
Question: How to override a linter cmd with function that return a table ?

### ISSUE THREAD

**Issue by riton** [mfussenegger/nvim-lint#412]
Hi,

I'm a brand new user of your plugin. I've discovered it through [LazyVim](https://www.lazyvim.org/plugins/linting).

I'm trying to migrate my previous configuration that was using [null-ls / none-ls](https://github.com/nvimtools/none-ls.nvim).

## My goal

My Python projects are using [Poetry](https://python-poetry.org/) as a package manager.

My goal is to adapt the `pylint` Python linter to have a behavior such that:
* if a `pylint` version is installed within my _poetry managed virtualenv_ , then use it
* if no `pylint` is available through `poetry` _virtualenv_ , then use whatever `pylint` is available.

## How I was achieving this with `null-ls`

My `null-ls` config has allowed me to achieve what I want, with this configuration:

```lua
[...]
        nls.builtins.diagnostics.pylint.with({
          command = function()
            local return_code = os.execute("poetry run pylint --version 1>/dev/null 2>/dev/null")
            if return_code == 0 then
              return { "poetry", "run", "pylint" }
            end
            return "pylint"
          end,
        }),
[...]
```

The `pylint` command executed by `neovim` is `poetry run pylint` if `pylint` is available within the project _virtualenv_.

## Porting this configuration to your plugin

I've tried to port the logic above to your plugin with:

```lua
return {
  "mfussenegger/nvim-lint",
  opts = {
    linters_by_ft = {
      python = {
        "pylint",
      },
    },
    linters = {
      pylint = {
        cmd = function()
          local return_code = os.execute("poetry run pylint --version 1>/dev/null 2>/dev/null")
          if return_code == 0 then
            return {
              "poetry",
              "run",
              "pylint",
            }
          end
          return "pylint"
        end,
      },
    },
  },
}
```

A configuration like this one throws the following error:

```
~/.local/share/nvim/lazy/nvim-lint/lua/lint.lua:218: bad argument #1 to 'spawn' (string expected, got table)│
```

I understand why this error is raised since `uv.spawn()` is used.

## Where I am now ?

I've created a _dummy shell wrapper_ such as:

```
/bin/bash -e
exec poetry run pylint "${*}"
```

and the plugin configuration is now returing `return "/path/to/poetry_run_pylint_wrapper.sh"` instead of `return {"poetry", "run", "pylint"}`.

This is working but I'm wondering how I could achieve my goal without this wrapper.

Thanks in advance for your time.

Regards

**Comment by mfussenegger** [comment]
`cmd` needs to be a single string and the arguments need to go into `args`.

You could return the whole linter as function to evaluate `poetry run` and then set both options depending on the result.
The compiler linter does that for example:

https://github.com/mfussenegger/nvim-lint/blob/aa95105d8b0c14920599e094407b0a4955a843b5/lua/lint/linters/compiler.lua#L4-L28
