### ISSUE TITLE
How to Pass Arguments to Linters?

### ISSUE THREAD

**Issue by FOSSilizedDaemon** [mfussenegger/nvim-lint#43]
I was going to use this to run shellcheck for POSIX script (i.e. shellcheck -s sh <file>), but I can't find how to pass arguments to my linters. Is this supported?

**Comment by mfussenegger** [comment]
See https://github.com/mfussenegger/nvim-lint/issues/31

**Comment by FOSSilizedDaemon** [comment]
@mfussenegger I tried something similar

```
nvim_linter = require 'lint'
nvim_linter.linters.shellcheck.args = { '-s', 'sh' }
nvim_linter.linters_by_ft = {
    sh = {'shellcheck'},
}
```

but for some reason now `shellcheck` does not run. Do I have the correct name to use in the `linters.shellcheck.args`?

**Comment by mfussenegger** [comment]
`shellcheck` sets `--format json` and `-` (to read from stdin). You need to preserve these two settings. The following should work:

```lua
require('lint').linters.shellcheck.args = {'-s', 'sh', '--format', 'json', '-' }
```

**Comment by FOSSilizedDaemon** [comment]
@mfussenegger That works thank you!
