### ISSUE TITLE
How to use flake8 as python linter?

### ISSUE THREAD

**Issue by jonahfang** [mfussenegger/nvim-lint#433]
Anyone can provide working example? Thanks in advance.

**Comment by msyavuz** [comment]
This is my config and it works
`
local lint = require "lint"

lint.linters_by_ft = {
    markdown = { "markdownlint" },
    javascript = { "eslint_d" },
    typescript = { "eslint_d" },
    javascriptreact = { "eslint_d" },
    typescriptreact = { "eslint_d" },
    lua = { "luacheck" },
    python = { "flake8" },
    gdscript = { "gdlint" },
    gitcommit = { "commitlint" },
}


vim.api.nvim_create_autocmd({ "BufEnter", "BufWritePost" }, {
    callback = function()
        lint.try_lint()
    end,
})
`

**Comment by jonahfang** [comment]
@msyavuz Thans! I follow your recommended configuration and have error like this:

```
Error running flake8: ENOENT: no such file or directory
```

I use `nvie/vim-flake8` now and it works:

```
            let cwd = getcwd()
            let g:flake8_cmd = "python -m flake8 --config " . cwd . "/.flake8rc"
            autocmd BufWritePost *.py call flake8#Flake8()
            let g:no_flake8_maps = 1

```

**Comment by msyavuz** [comment]
flake8 needs to be in your $PATH. You can install flake8 either through mason or manually.

**Comment by bvolkmer** [comment]
I just had the same problem. Wouldn't it be more stable to use `python3 -m flake8`?
