### ISSUE TITLE
Add a custom configurable global message format for all linters

### ISSUE THREAD

**Issue by rootex-** [mfussenegger/nvim-lint#440]
Hi, thanks for the great plugin 🤝

It would be great to have an ability to add a custom configurable global message format for all linters. 

For instance, for flake8 the diagnostic buffer shows this:
```
SyntaxError: invalid syntax [E999]
```

I would like to have the ability to add custom information (a plugin name, a linter name) to be able to see from what plugin the linter error comes:
```
SyntaxError: invalid syntax [E999] [nvim-lint] [flake8]
```
or perform a few rearrangements like this:
```
[nvim-lint] [E999] SyntaxError: invalid syntax [flake8]
```

So one could see what plugin provides linting right now and the linter name. 
It was also possible in null-ls as far as I remember.

**Comment by mfussenegger** [comment]
See the `format` function under `:h vim.diagnostic.config()`
nvim-lint is only a diagnostic provider. Consumption & display is part of neovim itself
