### ISSUE TITLE
The default SQL dialect in SQLFluff

### ISSUE THREAD

**Issue by chasing-freedom** [mfussenegger/nvim-lint#441]
https://github.com/mfussenegger/nvim-lint/blob/962a76877a4479a535b935bd7ef35ad41ba308b2/lua/lint/linters/sqlfluff.lua#L3-L7

The default SQL dialect  should change from `postgres` to `ansi`

> ANSI
> This is the base dialect which holds most of the definitions of common SQL commands and structures. If the dialect which you’re actually using isn’t specifically implemented by SQLFluff, using this dialect is a good place to start.
[Doc of SQLfluff](https://docs.sqlfluff.com/en/stable/dialects.html#ansi)

**Comment by fbuchlak** [comment]
I do agree. There's no reason to use other dialect than `ansi` as default.
