### ISSUE TITLE
Regression: `85108b3` causes "EMFILE: too many files open" errors

### ISSUE THREAD

**Issue by chrisgrieser** [mfussenegger/nvim-lint#448]
I confirmed by bisecting that commit `85108b3` is responsible for causing this error.

A few minutes after nvim startup, I get multiple "EMFILE: too many files open" errors (1st image). The issue even seems to be "cascading" in such a way that various other plugins that run jobs like lualine are also affected (2nd image). A restart fixes the error, but only for a few minutes.

Even copying to the system clipboard (`"+`) becomes impossible once the error has occurred. Any attempt to do so results in "clipboard: error: -1" (which is why I had to make screenshots instead of copypasting the full errors)

![Pasted image 2023-11-04 at 16 07 05@2x](https://github.com/mfussenegger/nvim-lint/assets/73286100/e5b91c18-e715-4b1b-ae00-d88c8d8dd6ad)

![Pasted image 2023-11-04 at 16 09 31@2x](https://github.com/mfussenegger/nvim-lint/assets/73286100/2d252ed6-909b-4b61-8579-a40404145a62)

```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1697887905
macOS 14.1
```

**Comment by mfussenegger** [comment]
Could you try an apply the following diff and check if it still happens?

```diff
diff --git a/lua/lint.lua b/lua/lint.lua
index 0acf8bb..d1e7794 100644
--- a/lua/lint.lua
+++ b/lua/lint.lua
@@ -114,16 +114,14 @@ local linter_proc_mt = {
 function LintProc:publish(diagnostics)
   -- By the time the linter is finished the user might have deleted the buffer
   if api.nvim_buf_is_valid(self.bufnr) and not self.cancelled then
     vim.diagnostic.set(self.ns, self.bufnr, diagnostics)
   end
-  self.stdout:shutdown(function()
-    self.stdout:close()
-  end)
-  self.stderr:shutdown(function()
-    self.stderr:close()
-  end)
+  self.stdout:shutdown()
+  self.stdout:close()
+  self.stderr:shutdown()
+  self.stderr:close()
 end
 
 
 function LintProc:start_read()
   local linter_proc = self
```

**Comment by mfussenegger** [comment]
I managed to create a failing test case without that change, so I guess it should be fixed with https://github.com/mfussenegger/nvim-lint/pull/449

**Comment by chrisgrieser** [comment]
thx for the quick fix!
