### ISSUE TITLE
BUG: mypy | numpy.typing.mypy_plugin

### ISSUE THREAD

**Issue by tomhampshire** [mfussenegger/nvim-lint#452]
nvim-lint: bd9bcc0937614cd94c5bde56f110ddc15a76c08c
mypy: 1.6.1
numpy: 1.25.2

Using a simple mypy.ini file:
```
[mypy]
plugins = numpy.typing.mypy_plugin
```

causes all mypy linting using nvim-lint to fail. All other linters will provide error/warning messages as expected, however, all messages from mypy are missing. Removing the numpy typing plugin from the mypy.ini file resolves the issue, and mypy linting messages are then provided as expected.

**Comment by mfussenegger** [comment]
This sounds like a mypy problem?

**Comment by tomhampshire** [comment]
Perhaps. However, there are no issues running mypy directly on the CLI, nor on our CI/CD server.

**Comment by tomhampshire** [comment]
Apologies. It turns out this was a teething problem with another plugin, and not an issue with mypy or nvim-lint. Closing the issue.
