### ISSUE TITLE
Eslint error when .eslint.json doesn't exist.

### ISSUE THREAD

**Issue by matthewrosse** [mfussenegger/nvim-lint#454]
Hello, I get an error `Error detected while processing BufWritePost Autocommands for "*":
Error running eslint: ENOENT: no such file or directory`. Is there a way not to trigger linter if it cannot find its configuration file? Because in some quick and dirty projects I don't setup eslint and its annoying when it shows the error on every save.

**Comment by caiyanhu** [comment]
I use lerna to manage projects sometimes, if I have installed eslint for example in root, the inner project will still report the above error. Seems like it won't look up eslint in upper space.

**Comment by mfussenegger** [comment]
`try_lint` has an `ignore_errors` option to ignore command-not-found errors: `require("lint").try_lint(nil, { ignore_errors = true })`
