### ISSUE TITLE
Formatting and auto fixing suport

### ISSUE THREAD

**Issue by lcmen** [mfussenegger/nvim-lint#456]
Hello!
Thank you for writing lua-based ale alternative ♥️. I have one question as it's not clear for me from the readme (I'm sorry if this already has been asked and answered 🙈): does this plugin support formatting as well?

I'm specifically looking at the case where both: prettier and eslint fix should be run on save on JS / TS file.

Thank you in advance for answering my question.

**Comment by gegoune** [comment]
Nope, it doesn't. It only shows diagnostics from configured linters. 

You can use amazing conform.nvim for formatting and fixing.

**Comment by lcmen** [comment]
Thank you @gegoune for quick reply 🙏! I wasn't aware of `conform.nvim`. With these 2 options, I should be able to replicate my ale-based linting setup 🚀.
