### ISSUE TITLE
cSpell code action is not working

### ISSUE THREAD

**Issue by Innei** [mfussenegger/nvim-lint#459]
Hi, I ran into a trouble.

I added cSpell to global linter. And It lint works, but no code action given.

<img width="820" alt="image" src="https://github.com/mfussenegger/nvim-lint/assets/41265413/482d5f55-322e-4d51-bcaa-ab032c884a3c">
<img width="697" alt="image" src="https://github.com/mfussenegger/nvim-lint/assets/41265413/cce9bb9b-921d-465e-9ac7-958434e35952">

This is my config.

```
return {
  {
    "mfussenegger/nvim-lint",
    opts = {
      -- Event to trigger linters
      events = { "BufWritePost", "BufReadPost", "InsertLeave" },
      linters_by_ft = {
 
        ["*"] = { "cspell" },
 
      },
    
    },
  },
}

```

**Comment by msyavuz** [comment]
I am pretty sure that is outside the scope of this plugin. I think the [community fork of null-ls](https://github.com/nvimtools/none-ls.nvim) has code actions. 
Relevant [comment](https://github.com/mfussenegger/nvim-lint/pull/4#issuecomment-813925893)

**Comment by guoliang** [comment]
is there alternative for that feature beside `null-ls/none-ls` the idea of using nvim-lint is to move away from the previous plugin I think.

**Comment by mfussenegger** [comment]
> the idea of using nvim-lint is to move away from the previous plugin I think.

No that's not the idea of nvim-lint. The idea of nvim-lint is to provide linting capabilities.
Fixing/code-actions/formatting  or whatever is not in scope.

See also https://github.com/mfussenegger/nvim-lint/issues/5
