### ISSUE TITLE
cppcheck: Linter command cppcheck exited with code 1

### ISSUE THREAD

**Issue by ilAYAli** [mfussenegger/nvim-lint#46]
cppcheck fails if `compile_commands.json` is not in build/

this fixes the problem for me:
```
diff --git a/lua/lint/linters/cppcheck.lua b/lua/lint/linters/cppcheck.lua
index 0908ca1..259e6fb 100644
--- a/lua/lint/linters/cppcheck.lua
+++ b/lua/lint/linters/cppcheck.lua
@@ -4,7 +4,7 @@ return {
   stdin = false,
   args = {
     '--enable=warning,style,performance,information', '--language=c++',
-    '--project=build/compile_commands.json', '--inline-suppr', '--quiet',
+    '--inline-suppr', '--quiet',
     '--cppcheck-build-dir=build', '--template={file}:{line}:{column}: [{id}] {severity}: {message}'
   },
   stream = 'stderr',
   ```

**Comment by mfussenegger** [comment]
@wbthomason Does removing the `--project=build/compile_commands.json'` make sense to you?

**Comment by ilAYAli** [comment]
Yes, I think that makes sense.
`cppcheck` will successfully execute without `—project` and `compile_commands.json` in ./build.
 I work on several projects where `compile_commands.json` is in the root dir, so it would be better if the default config “just works”, and have the option to supply additional arguments if needed/desired

**Comment by mfussenegger** [comment]
I removed the setting

**Comment by wbthomason** [comment]
Sorry, somehow missed this until now. Removing this argument should be fine; I was following ALE's setup when writing this linter config, but it seems that specifying the project is not necessary (at least, in my very limited testing).

**Comment by wbthomason** [comment]
That said: having the option to specify this, e.g. via something like #20, would be helpful. I do get warnings that `cppcheck` cannot find all the include files in my project when the `--project` argument is missing.

**Comment by mfussenegger** [comment]
I think it should be possible to do something like this to add the argument:

```lua
local cppcheck = require('lint.linters.cppcheck')
table.insert(cppcheck.args, '--project=build/compile_commands.json')
```
