### ISSUE TITLE
Backslash in the Windows path causes missing error report

### ISSUE THREAD

**Issue by kkpattern** [mfussenegger/nvim-lint#480]
Thanks for this nice plugin.

When used on the Windows platform, I noticed that the backslash in the Windows path caused missing error report. The corresponding code is here: https://github.com/mfussenegger/nvim-lint/blob/master/lua/lint/parser.lua#L72

I think we can normalize the path by replacing all backslashes with slashes. I tested with the following code and it worked:

```lua
      local normalized_path = string.gsub(path, '\\', '/')
      local normalized_buffer_path = string.gsub(buffer_path, '\\', '/')
      if normalized_path ~= normalized_buffer_path then
        return nil
      end
```

**Comment by replicaJunction** [comment]
I can confirm this issue affects Mypy on Windows, and the fix @kkpattern suggested works well.

Since this issue is labelled as needs contribution, I went ahead and opened a PR to fix it, though instead of normalizing the paths using `string.gsub`, I used the built-in function `vim.fs.normalize`.
