### ISSUE TITLE
Bug: Running linters are now a representation of which linter has ran, not currently running.

### ISSUE THREAD

**Issue by arnevm123** [mfussenegger/nvim-lint#484]
Hi,

Thanks for getting my PR into the codebase (#402 ).
I have found that the behavior has changed since I've made the PR. When I made the PR the running linter was shown as long as it was running, now it seems to just show which linter has ran on our buffer. Not sure if this is wanted behavior from the `running_procs_by_buf`. I can look into this some time if it's not, the change has happened since the fork on my gh, which branched of here: https://github.com/mfussenegger/nvim-lint/commit/7d273c3963c923a194bfd31ab498dfd6c0b2cae8, I can have a look with git-bisect later :smile: 

Kind regards!

**Comment by mfussenegger** [comment]
Can you try with https://github.com/mfussenegger/nvim-lint/pull/489 ?

**Comment by arnevm123** [comment]
Yep, that fixed it thanks!
