### ISSUE TITLE
Diagnostic config per linter?

### ISSUE THREAD

**Issue by screendriver** [mfussenegger/nvim-lint#485]
In [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) it was/is possible to [specifiy](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/0010ea927ab7c09ef0ce9bf28c2b573fc302f5a7/doc/CONFIG.md?plain=1#L124) diagnostic display options per linter. With that approach one could hide the virtual text for some linters but let it shown for others. For example to show ever lint error as virtual text but hide `cspell` messages (because they are more a hint) a configuration would look like this:

```lua
null_ls.builtins.diagnostics.cspell.with({
  diagnostic_config = {
    virtual_text = false,
  }
})
```

Is that also possible in `nvim-lint` or does anyone know a way how to achieve that?

**Comment by mfussenegger** [comment]
Per linter configuration wasn't possible because the namespaces weren't exposed. I changed that with https://github.com/mfussenegger/nvim-lint/pull/490 and https://github.com/mfussenegger/nvim-lint#display-configuration
