### ISSUE TITLE
Cppcheck v2.12.0 failing

### ISSUE THREAD

**Issue by tomhampshire** [mfussenegger/nvim-lint#492]
Recent versions of Cppcheck (v2.12.0) are failing with nvim-lint

**Comment by kapkanov** [comment]
I'm going to describe my problem and a solution of it, I hope it'll help you

### My setup

- `nvim v0.9.4`
- `nvim-lint` 3ffa176
- `cppcheck 2.12.1`
- `OS OpenSUSE Leap 15.5`

### Problem

No inline diagnostics, only the message `Linter command 'cppcheck' exited with code: 1` on the nvim output panel

### Solution

`nvim-lint` [passes --cppcheck-build-dir=build](https://github.com/mfussenegger/nvim-lint/blob/3ffa176628fe49e74f47992757016b7371a9b86b/lua/lint/linters/cppcheck.lua#L26) to the `cppcheck` command, so after I've created a `build` directory within the same directory where the C source file is located, the diagnostics appeared. You can change the passed arguments to suite your needs of course

**Comment by mfussenegger** [comment]
@ismasou could you create a PR for that change?
