### ISSUE TITLE
stylelint doesn't lint

### ISSUE THREAD

**Issue by kapral18** [mfussenegger/nvim-lint#500]
![CleanShot 2024-01-02 at 13 29 53](https://github.com/mfussenegger/nvim-lint/assets/1625373/6efca8ee-438f-4a91-945b-33715de22487)

I don't get any diagnostics for existing error

Seems like `stdout.read_start` callback is called once https://github.com/mfussenegger/nvim-lint/blob/4dbc7ec60b33b656f7c54bb945671a55b18699f2/lua/lint.lua#L147

and here https://github.com/mfussenegger/nvim-lint/blob/4dbc7ec60b33b656f7c54bb945671a55b18699f2/lua/lint.lua#L77 both args `err, chunk` are `nil`

My config https://github.com/kapral18/config.nvim/blob/dee5f388194a315bfbf7d8587b7d3ce8de9dbe60/lua/plugins/css.lua#L42 (lazyvim based)

Nvim: nvim 0.10.0

**Comment by jmpolom** [comment]
I have noticed this issue as well upon updating to neovim 0.9.5. nvim-lint configured for stylelint did not seem to behave properly on an older neovim version but after an update no output is produced even when purposely broken css is inserted. Manually running stylelint against the file with broken css identifies the flaws and prints them to the CLI.

At a loss for how to debug this further.

**Comment by thatanjan** [comment]
It also doesn't work. I am using NVIM v0.9.4

**Comment by jmpolom** [comment]
Based on some very crude attempts at debugging this issue, it appears in my case the parser function isn't being called for some reason.

**Comment by jmpolom** [comment]
Decided to dig in a little further with osv and nvim-dap.

It appears that the linter isn't being called with the designated command line arguments and luv is only starting `stylelint` with no flags/args. The options table getting passed to `uv.spawn` looks good though?

I did check another linter (tidy) and it appeared to start with the correct CLI args.

Seems like a possible bug with luv? I did update to whatever the latest libuv/luv/neovim is in homebrew. I am rather stumped.

**Comment by jmpolom** [comment]
I observe the opposite results even when testing with the same flags as nvim-lint calls stylelint with... :( I am on arm64 macOS. What operating system did you test from? What version of stylelint? Why would stylelint output to a different stream?

There is an option for `both` for the stream but I could see that being problematic potentially?

**Comment by kapral18** [comment]
@jmpolom 
stylelint - 11.1.1
macos sonoma
mbp max m1, so arm64 as well

I just tested with latest version 16 and it indeed yields from stderr

So apparently they switched from some version from stdout to stderr

**Comment by kapral18** [comment]
yepp here is it https://github.com/stylelint/stylelint/releases/tag/13.6.0

**Comment by jmpolom** [comment]
I also see a reference in the migration guide for 16 about problems printing to `stderr`: https://github.com/stylelint/stylelint/blob/main/docs/migration-guide/to-16.md#breaking-changes

Unsure when it changed but it seems most certain it did.

**Comment by kapral18** [comment]
@jmpolom  I was wrong they didn't change reporting errors to stderr from v13 they starting reporting the very fact of cli error to stderr, but the linting errors are still reported to stdout all the way to v15(incl). Only v16 the latest one actually changed that behavior

**Comment by jmpolom** [comment]
I had an older version installed that produced garbage output via this plugin but upon updating stopped producing any output via nvim-lint. I am guessing I went from 15something->16.

Either way looks like we have this one licked? Just make a manual change locally until a PR gets merged to fix this.

**Comment by kapral18** [comment]
well currently I have like 20 projects all using different versions of stylelint and I switch between them, so the only thing that works would probably be having some custom keymap to reinitialize linter per project with stdout or stderr. But I assume this is not a unique problem for stylelint since most likely other linters have similar issues that people haven't come across yet.
Anyways thanks for investigations. Closing it
