### ISSUE TITLE
Options for pylintrc files?

### ISSUE THREAD

**Issue by mesa123123** [mfussenegger/nvim-lint#509]
Hey man loving the plugin!

I'm just wondering if pylint can have a rcfile tacked onto its args capabilities?
![image](https://github.com/mfussenegger/nvim-lint/assets/22901019/a924df49-d44d-4764-8309-e27876e81448)
Currently getting this error when I'm implementing my code:
![image](https://github.com/mfussenegger/nvim-lint/assets/22901019/84939889-24f5-4964-835f-5b3a5ec36031)
Am I doing something wrong or is this just somehting the parser can't do yet?
I think I could add some kind of logic in for this?

**Ok tried something different and just have:**
![image](https://github.com/mfussenegger/nvim-lint/assets/22901019/76c768cc-2d9d-4e25-a4b8-b030e4710b96)
So no matter what I'm passing  { "-f", "json" } to the args pylint
Same error popped up

**Tried this too:**
![image](https://github.com/mfussenegger/nvim-lint/assets/22901019/4357af3a-7614-4ec3-9165-c225df101d58)
and pylint didn't load at all?
![image](https://github.com/mfussenegger/nvim-lint/assets/22901019/8236a414-9f34-45e8-ac4d-647213266cf1)
There should be at least a function docstring not found error right?

**Next Tried This**
![image](https://github.com/mfussenegger/nvim-lint/assets/22901019/8d1faf00-2dc1-4dd6-b6b8-0621c1d5cb99)
and pylint didn't seem to load this time either

**And lastly this**
![image](https://github.com/mfussenegger/nvim-lint/assets/22901019/367bb53e-b129-4312-9306-28cd67e68381)
And pylint worked perfectly...
![image](https://github.com/mfussenegger/nvim-lint/assets/22901019/3753b6b8-95f0-46a1-9c8f-bf6e9a7bd400)

**However, this seemed to work**
![image](https://github.com/mfussenegger/nvim-lint/assets/22901019/b9f8c461-3970-49bb-a0c9-9bdff7a4d548)
But then I'm unsure of how to make sure that it always looks for the pylintrc in the project directory?

Because as soon as I went into a child module and ran from there pylint seems to crash again:
![image](https://github.com/mfussenegger/nvim-lint/assets/22901019/d0f844d7-bdd0-48d2-b799-3352800e2131)

This is the pylinrc contents btw:
![image](https://github.com/mfussenegger/nvim-lint/assets/22901019/b8f85867-a6cd-4a4c-8cae-d4ac0f68ebbe)

**Comment by maxspahn** [comment]
Hi @mesa123123 ,

I had the same issue but with the help of chatgpt :sunglasses:, I came up with that solution:

```lua
function file_exists_in_parent(filename)
    local function search_in_directory(dir)
        local file_path = dir .. "/" .. filename
        local file = io.open(file_path, "r") -- Try to open the file in read mode
        if file then
            file:close() -- Close the file handle
            return true, file_path -- File exists, return its path
        else
            return false -- File doesn't exist in this directory
        end
    end

    local current_dir = os.getenv("PWD") or os.getenv("CD") or "." -- Get the current directory

    repeat
        local found, file_path = search_in_directory(current_dir)
        if found then
            return true, file_path -- File exists in the current directory or its ancestor
        else
            local parent_dir = current_dir:gsub("[^/\\]+$", ""):sub(0, -2)
            if parent_dir and parent_dir ~= current_dir then
                current_dir = parent_dir -- Move to the parent directory
            else
                break -- Reached the root directory
            end
        end
    until false

    return false -- File not found in the parent directory or its ancestors
end

local file_name = ".pylintrc"
local found, file_path = file_exists_in_parent(file_name)
if found then
  print("Found pylintrc", file_path:sub(0, -1))
  local pylint = require('lint').linters.pylint
  pylint.args = {
    '-f', 'json',
    '--rcfile', file_path,
  }
else
  print("No pylintrc file found. Using default config.")
end

```

That works except for it does not reload the pylintrc file, if you change directory while being in vim using nerdtree for example.

**Comment by mfussenegger** [comment]
> I'm not going to merge any complex root detection logic. The only thing I'd accept is a simple `vim.fs.find`, nothing more than that.
> 
> Most linters pick up config files in the current working directory per default, and don't require _any_ custom logic at all. I thought that's also the case for pylint, which means you have to make sure that nvim has the right working directory set, or you call `try_lint` with the `cwd` option set.
> 
> Root dir and projection management heuristics are out of scope of nvim-lint.

See also https://github.com/mfussenegger/nvim-lint/issues/482#issuecomment-1999185606
