### ISSUE TITLE
Add oxlint, the faster eslint alternative

### ISSUE THREAD

**Issue by msiirodrigo2670** [mfussenegger/nvim-lint#531]
[OXC Linter Documentation](https://oxc-project.github.io/docs/guide/usage/linter.html)

## Features

- **50 - 100 times faster than ESLint**, and scales with the number of CPU cores ([benchmark](https://github.com/oxc-project/bench-javascript-linter)).
- Over 200 rules with a growing list from eslint, typescript, eslint-plugin-react, eslint-plugin-jest, eslint-plugin-unicorn, and eslint-plugin-jsx-a11y.
- Supports [`.eslintignore`](https://eslint.org/docs/latest/use/configure/ignore#the-eslintignore-file).
- Supports [ESLint comment disabling](https://eslint.org/docs/latest/use/configure/rules#disabling-rules).
- Lint `<script>` content of `.vue`, `.astro`, `.svelte` files by default.

**Comment by fbuchlak** [comment]
For easier implementation I'm waiting for [1462](https://github.com/oxc-project/oxc/issues/1462) with this.

**Comment by andrew-t-james-core** [comment]
Happy to contribute toward this when the time comes.

**Comment by catgoose** [comment]
The time has come!

https://github.com/oxc-project/oxc/issues/1462 has been merged.

**Comment by jellydn** [comment]
Here is how I set up with my neovim. Just leave here if anyone want to take a try.

```lua
return {
  {
    "mfussenegger/nvim-lint",
    opts = {
      linters_by_ft = {
        javascript = { "oxlint" },
        typescript = { "oxlint" },
        javascriptreact = { "oxlint" },
        typescriptreact = { "oxlint" },
      },
    },
    init = function()
      -- Register oxlint, based on `lua/lint/linters/jshint.lua`
      require("lint").linters.oxlint = {
        name = "oxlint",
        -- cargo install --features allocator --git https://github.com/oxc-project/oxc oxc_cli
        cmd = "oxlint", // NOTE: this is using oxlint bin from cargo
        stdin = false,
        args = { "--format", "unix" },
        stream = "stdout",
        ignore_exitcode = true,
        parser = require("lint.parser").from_errorformat("%f:%l:%c: %m", {
          source = "oxlint",
          severity = vim.diagnostic.severity.WARN,
        }),
      }
    end,
  },
}
```

**Comment by catgoose** [comment]
> Here is how I set up with my neovim. Just leave here if anyone want to take a try.
> 
> ```lua
> return {
>   {
>     "mfussenegger/nvim-lint",
>     opts = {
>       linters_by_ft = {
>         javascript = { "oxlint" },
>         typescript = { "oxlint" },
>         javascriptreact = { "oxlint" },
>         typescriptreact = { "oxlint" },
>       },
>     },
>     init = function()
>       -- Register oxlint, based on `lua/lint/linters/jshint.lua`
>       require("lint").linters.oxlint = {
>         name = "oxlint",
>         -- cargo install --features allocator --git https://github.com/oxc-project/oxc oxc_cli
>         cmd = "oxlint", // NOTE: this is using oxlint bin from cargo
>         stdin = false,
>         args = { "--format", "unix" },
>         stream = "stdout",
>         ignore_exitcode = true,
>         parser = require("lint.parser").from_errorformat("%f:%l:%c: %m", {
>           source = "oxlint",
>           severity = vim.diagnostic.severity.WARN,
>         }),
>       }
>     end,
>   },
> }
> ```

What is interesting is if you try this in a vue SFC with the template tags before the script tags, oxlint is reporting the position of the warning offset from the top of the file in the template relative to where the setup tags start:

![image](https://github.com/mfussenegger/nvim-lint/assets/21010072/458dde4f-3442-41f5-b02e-d161105b3b03)
