### ISSUE TITLE
Integration Issue with cpplint and nvim-lint: No Linting Results Displayed

### ISSUE THREAD

**Issue by alitokur** [mfussenegger/nvim-lint#534]
I am trying to integrate cpplint with nvim-lint for C++ linting but linting results are not displayed after saving files.

Steps to Reproduce:

1- Install nvim-lint using packer with the following line in my packer configuration file:
```lua
use 'mfussenegger/nvim-lint'ua
use 'mfussenegger/nvim-lint'
```
2- Configure nvim-lint to use cpplint for markdown file types (note: assuming you meant C++ file types, but the provided configuration targets markdown) as shown below:
```lua
require('lint').linters_by_ft = {
  markdown = {'cpplint', }
}
```
3- Set up an autocommand to trigger linting on BufWritePost:

```lua
vim.api.nvim_create_autocmd({ "BufWritePost" }, {
  callback = function()
    require("lint").try_lint()
  end,
})
```
4- Install cpplint via mason

note: I use cmake to generate a compile_commands.json file under the build directory.

**Comment by mfussenegger** [comment]
> Configure nvim-lint to use cpplint for markdown file types (note: assuming you meant C++ file types, but the provided configuration targets markdown) as shown below:


That's just an example for markdown. If you use different linters for different filetypes you need to change it accordingly
