### ISSUE TITLE
get_running() not displaying any  info

### ISSUE THREAD

**Issue by mairs8** [mfussenegger/nvim-lint#543]
i have added the below keybind. when i activate it, nothing happens. 

`vim.keymap.set("n", "<leader>x", function() require("lint").get_running() end, { desc = "get running linters for current buffer" })
`

I am pretty sure that my linters are running since ConformInfo returns: 
> Formatters for this buffer:
> LSP: kotlin_language_server
> ktlint ready (kotlin) /nix/store/0ladyg0hhsims66vrdqwfpia9whn98wb-ktlint-1.1.0/bin/ktlint

If there is something wrong in my setup and there are no linters connected, shouldn't the get_running() notify that there are 'no linters' or some other type of notifcation to the user signalling it is not working? At the moment it seems to display nothing in these cases which is not helpful to the user.

**Comment by mfussenegger** [comment]
get_running only shows the _currently_ running linters. If they're fast you won't see any output unless you run it immediately after calling `try_lint`.

> shouldn't the get_running() notify that there are 'no linters' or some other type of notifcation to the user signalling it is not working? 

If that's what you want you can add a fallback if the result is empty.
