### ISSUE TITLE
Configuring default diagnostic severity level of a linter

### ISSUE THREAD

**Issue by lukoshkin** [mfussenegger/nvim-lint#557]
Hey!
How can I change the default diagnostic severity level of a linter? I am particularly interested in changing all INFO diagnostics of cspell to HINT

**Comment by doums** [comment]
Exact same question here

**Comment by mfussenegger** [comment]
I have no plans to add a default setting but I'd be open to change the default of specific linters if there is a good rationale

**Comment by lukoshkin** [comment]
@mfussenegger thanks for adding `util.wrap` !!
