### ISSUE TITLE
Bug: plugin doesn't find buf tool

### ISSUE THREAD

**Issue by emersonfbarros** [mfussenegger/nvim-lint#561]
I have the following keymap to trigger the linter

```
local lint = require 'lint'

vim.keymap.set('n', '<leader>cl', function()
    lint.try_lint()
    end, { desc = '[C]ode [L]int' })

lint.linters_by_ft = {
  proto = { 'buf' },
}
```

but in proto files when try lint with buf the following error occurs

![image](https://github.com/mfussenegger/nvim-lint/assets/72613326/91a515e5-bc60-4830-8aed-c9ec4df23c5d)

for some reason nvim-lint can't find buf...

**Comment by mfussenegger** [comment]
`buf` is not listed in https://github.com/mfussenegger/nvim-lint?tab=readme-ov-file#available-linters - it doesn't exist.

**Comment by martinbjeldbak** [comment]
@emersonfbarros in case you haven't solve this yet, you most likely want to use `buf_lint`, which executes the `buf` binary

See source: https://github.com/mfussenegger/nvim-lint/blob/master/lua/lint/linters/buf_lint.lua

```lua
local lint = require 'lint'

vim.keymap.set('n', '<leader>cl', function()
    lint.try_lint()
    end, { desc = '[C]ode [L]int' })

lint.linters_by_ft = {
  proto = { 'buf_lint' },
}
```

**Comment by emersonfbarros** [comment]
@martinbjeldbak after search on the repo base i have find exactly the same. thanks for the help!
