### ISSUE TITLE
error message every time i open or save a file which linter is not installed

### ISSUE THREAD

**Issue by daniele821** [mfussenegger/nvim-lint#569]
nvim-lint plugin report the following error message:

```
Error detected while processing BufEnter Autocommands for "*":
Error running markdownlint: ENOENT: no such file or directory
```
every time i open or save a file which has a linter associated, but the linter is not installed.
For example i declare "shellcheck" as the linter for bash, but i do not install shellcheck, and then i try to open a bash file, the error message written above will show up once i open the file, and every time i save the file.

I would like if it was like conform (which takes care of formatting), where if you don't have the thing installed, it just doesn't run.

thanks

**Comment by ivanesmantovich** [comment]
Hi!
`try_lint` has an `ignore_errors` option to ignore command-not-found errors: `require("lint").try_lint(nil, { ignore_errors = true })`
#454
