### ISSUE TITLE
how to add the hl `DiagnosticUnnecessary` to unused var or package in ruff

### ISSUE THREAD

**Issue by ShIRannx** [mfussenegger/nvim-lint#573]
pyright like:
<img width="778" alt="image" src="https://github.com/mfussenegger/nvim-lint/assets/72802064/8b7e573d-7f72-4f6c-9a5f-aaff67ff979a">

nvim-lint using ruff like:
<img width="828" alt="image" src="https://github.com/mfussenegger/nvim-lint/assets/72802064/b74c6f9c-2faf-4190-bf6d-9d1dc09555a3">

seem, the pyright added an extra hl group `DiagnosticUnnecessary` to the unused var or package word.
how to i do that with nvim-lint?

**Comment by mfussenegger** [comment]
This would require a change in neovim to make the `_tags` attribute in the vim.Diagnostic structure public.
Once that gets added, the `ruff` linter here could get extended to set it depending on the provided error codes.
