### ISSUE TITLE
How to customize a linter

### ISSUE THREAD

**Issue by santoso-wijaya** [mfussenegger/nvim-lint#578]
For instance, in a LazyVim plugins/ folder:

```lua
return {
  {
    "mfussenegger/nvim-lint",
    opts = {
      linters = {
        markdownlint = {
          -- What attributes are supported here??
        },
      },
    },
  },
}
```

I wonder what attributes are supported for each of these specific linter options? Is that documented somewhere?

**Comment by mfussenegger** [comment]
See https://github.com/mfussenegger/nvim-lint?tab=readme-ov-file#customize-built-in-linters
To learn what arguments a particular linter supports you'll need to refer to its upstream documentation
