### ISSUE TITLE
`require("lint").get_running()` not returning anything

### ISSUE THREAD

**Issue by gennaro-tedesco** [mfussenegger/nvim-lint#583]
I am trying to output the linters that are active upon each buffer and I seemingly cannot get `require("lint").get_running()` to return any result (although the linters are active and all works fine): see example below

https://github.com/mfussenegger/nvim-lint/assets/15387611/23b60368-0b13-4644-a45d-8b7357b1e30f

you can see that `ruff` is active as a linter, producing the expected output, however the method `get_running()` does not return anything: the same holds true for any other filetype and/or linter.

Do I misunderstand how it is supposed to work or has any of the recent commits perhaps introduced a bug in said function (it should work, but it doesn't)?

**Comment by daniele821** [comment]
i was trying to write a function to show active linters in lualine, and i have the same problem. I have shellcheck running on sh files, but the method get_running() returns an empty table.

I also tried passing the current buffer, but it still returns an empty table

**Comment by daniele821** [comment]
update: it's a bug.

linters are stored in a variable the moment they are started, but that variable gets soon cleaned up for some reasons. I am trying to figure this out

**Comment by winter-again** [comment]
Sounds like [this](https://github.com/mfussenegger/nvim-lint/issues/543#issuecomment-1967549762)

**Comment by daniele821** [comment]
> Sounds like [expected behavior](https://github.com/mfussenegger/nvim-lint/issues/543#issuecomment-1967549762)

seeing that this already got report as a bug at least twice, it's at the very least a strange behaviour. I can understand why it is like this, but it would be nice to be able to always know what linters are corrently active on the current buffer

**Comment by mfussenegger** [comment]
Then use `require("lint").linters_by_ft[vim.bo.filetype] or {}`

**Comment by ooloth** [comment]
> Then use require("lint").linters_by_ft[vim.bo.filetype] or {}

Wouldn't that just show the linters that we've configured? Rather than confirming which linters succeeded in attaching?

I join others in hoping for similar behavior as `LspInfo`, `ConformInfo`, etc as a way to confirm which linters are actually active in a given buffer. For example, it would help when debugging why a configured linter doesn't seem to be doing anything.

**Comment by MartenBE** [comment]
I fixed it like this in lualine:

```lua
{
    -- Configured linters for the current file type
    function()
        local lint = require("lint")
        local configured_linters = lint.linters_by_ft[vim.bo.filetype] or {}
        local running_linters = lint.get_running() or {}

        if vim.tbl_isempty(configured_linters) then
            return ""
        end

        local names = {}
        for _, name in ipairs(configured_linters) do
            local display_name = name
            if vim.tbl_contains(running_linters, name) then
                display_name = display_name .. "  "
            end

            table.insert(names, display_name)
        end

        return "L:" .. table.concat(names, ",")
    end,
},
```

It shows the configured linters and adds a spinner icon to a linters name when that linter is running.
