### ISSUE TITLE
Actionlint lints all YAML files

### ISSUE THREAD

**Issue by devkvlt** [mfussenegger/nvim-lint#591]
https://github.com/mfussenegger/nvim-lint/pull/472 causes Actionlint to lint all YAML files instead of only GitHub action files. This occurs because using stdin prevents Actionlint from automatically detecting the appropriate files to lint. Reverting to the previous commit will resolve this issue.

**Comment by mfussenegger** [comment]
I don't see it linting other files. Only the stdin.

If you have a `linters_by_ft = { yaml = {"actionlint"}}` entry it will of course run on all yaml files.

You can avoid that by doing something like:

```
vim.filetype.add({
  pattern = {
    ['.*/.github/workflows/.*%.yml'] = 'yaml.ghaction',
    ['.*/.github/workflows/.*%.yaml'] = 'yaml.ghaction',
  },
})
```

And set `lint.linters_by_ft = { ghaction = {"actionlint"}}`

**Comment by devkvlt** [comment]
That's a cool trick, thanks.

Yeah I had `yaml = {"actionlint"}` but it worked fine previously, until I updated the plugin.

I think it might be a good idea to include that trick somewhere in the README, cause it's not really obvious for everyone 😄
