### ISSUE TITLE
Linter with name `markdownlint-cli2` not available

### ISSUE THREAD

**Issue by hyawara** [mfussenegger/nvim-lint#594]
![image](https://github.com/mfussenegger/nvim-lint/assets/31959238/4eeb1331-78c0-4b84-a016-713f7f3fa2e8)

config:

![image](https://github.com/mfussenegger/nvim-lint/assets/31959238/21f701d7-d95a-43d6-a33f-0a9f54446746)

mason:

![image](https://github.com/mfussenegger/nvim-lint/assets/31959238/3b127df2-791d-4c1d-a69b-889bcf48fac2)

**Comment by mfussenegger** [comment]
`:lua =require("lint").linters["markdownlint-cli2"]` works fine for me. Make sure you have the latest nvim-lint version.
