### ISSUE TITLE
Configuration for `selene`

### ISSUE THREAD

**Issue by v3natio** [mfussenegger/nvim-lint#603]
Hi, I've installed `selene` through `Mason`. This is my current configuration:

```lua
local present, lint = pcall(require, 'lint')
if not present then
  return
end

lint.linters_by_ft = {
  lua = { 'selene' },
  python = { 'pylint' },
}

local lint_augroup = vim.api.nvim_create_augroup('lint', { clear = true })
vim.api.nvim_create_autocmd({ 'BufEnter', 'BufWritePost', 'InsertLeave' }, {
  group = lint_augroup,
  callback = function()
    lint.try_lint()
  end,
})
```

Now, my issue is that I'm not sure how to properly set up `selene`. The thing is, I've got a `selene.toml` file in the `./nvim/` folder, and here are it's contents:

```toml
[selene]
base = "lua51"

[rules]
mixed_table = "allow"

[vim]
any = true
```

If I `cd` into the `./nvim/` directory from my terminal, and then open a `.lua` file, then selene works as expected. Otherwise, if I don't open it from that directory, then the configuration won't be loaded. `selene` itself does work, but the configuration to ignore the vim globals won't.

**Comment by v3natio** [comment]
In the meantime, I've found [this](https://github.com/folke/dot/blob/master/nvim/lua/plugins/lsp.lua) configuration by folke, here's a snippet:

```lua
  {
    "mfussenegger/nvim-lint",
    opts = {
      linters_by_ft = {
        lua = { "selene", "luacheck" },
      },
      linters = {
        selene = {
          condition = function(ctx)
            local root = LazyVim.root.get({ normalize = true })
            if root ~= vim.uv.cwd() then
              return false
            end
            return vim.fs.find({ "selene.toml" }, { path = root, upward = true })[1]
          end,
        },
        luacheck = {
          condition = function(ctx)
            local root = LazyVim.root.get({ normalize = true })
            if root ~= vim.uv.cwd() then
              return false
            end
            return vim.fs.find({ ".luacheckrc" }, { path = root, upward = true })[1]
          end,
        },
      },
    },
  },
```

**Comment by v3natio** [comment]
With the idea from the solution above I realized I could leverage `lsp`'s functionality to get the root directory of a project, and pass that onto the `cwd` argument of `nvim-lint`.

So instead of:
```lua
callback = function()
  lint.try_lint()
end,
```

we replace it with:
```lua
callback = function()
  local client = vim.lsp.get_clients({ bufnr = 0 })[1] or {}
  lint.try_lint(nil, { cwd = client.root_dir })
end,
```

This either takes the `cwd` from `lsp`, or won't set one at all, making it usable in all cases.

**Comment by DGotshalk** [comment]
So I tried your solution
`
local present, lint = pcall(require, 'lint')
if not present then
  return
end

lint.linters_by_ft = {
  lua = { 'selene' },

}

local lint_augroup = vim.api.nvim_create_augroup('lint', { clear = true })
vim.api.nvim_create_autocmd({ 'BufEnter', 'BufWritePost', 'InsertLeave' }, {
  group = lint_augroup,
  callback = function()
    local client = vim.lsp.get_clients({ bufnr = 0 })[1] or {}
    lint.try_lint(nil, { cwd = client.root_dir })
  end,
})
`
But it only finds the selene.toml file and its configuration after Write or Insert leave, not on Enter

**Comment by v3natio** [comment]
Hi @DGotshalk, that's due to the way those lsp functions work. I believe they're loaded on the `InsertEnter` event, not the `BufEnter` event which is the one I assume you're referring to. 

The only way, thatbI'm aware of, to get around this is to set up a recursive search for the root dir using some command as the snippet I showed previous to my answer. 

Maybe there's a way to have those lsp functions be loaded at `BufEnter` but I wouldn't know.

**Comment by elken** [comment]
```lua
lint.try_lint(nil, { cwd = client.root_dir or vim.fn.fnamemodify(vim.fn.finddir(".git", ".;"), ":h") })
```

Also works. Adjust the arguments to `vim.fn.finddir` accordingly based on whatever markers you want to use 😄

**Comment by DGotshalk** [comment]
@elken This works perfectly! Thank you so much

**Comment by BestChinchilla** [comment]
@elken OMG you are the best! Thank you <3

**Comment by sghng** [comment]
@v3natio Thanks for the great script! However, I noticed that in my setup, the first lsp that shows up is copilot instead of server corresponds to the language. I created a util functino to solve this:

```lua
---Get the root directory from LSP for the **current** buffer
function _G.root()
	for _, client in ipairs(vim.lsp.get_clients({ bufnr = 0 })) do
		if client.name ~= "copilot" and client.root_dir then
			return client.root_dir
		end
	end
	return nil
end
```
