### ISSUE TITLE
HELP: Looking for a way to toggle a specific linter

### ISSUE THREAD

**Issue by M-Xue** [mfussenegger/nvim-lint#611]
I want to toggle `cspell` on and off since I don't always want it's diagnostics on cluttering my buffers. Is there any easy recipe or way I can follow to achieve this?

**Comment by Strongleong** [comment]
Same here

**Comment by replicaJunction** [comment]
I use `try_lint(names)` as described in the [readme](https://github.com/mfussenegger/nvim-lint?tab=readme-ov-file#usage) to set up an autocmd and a keybind with different linters. For example, inside the plugin's configuration:

```lua
local on_demand_linters = { "mypy", "pylint" }
local auto_linters = { "mypy" }

local function lint_autocmd()
  require("lint").try_lint(auto_linters)
end

local function lint_on_demand()
  require("lint").try_lint(on_demand_linters)
end

local lint_augroup = vim.api.nvim_create_augroup("user-nvim-lint", { clear = true })
vim.api.nvim_create_autocmd(opts.autocmd.events, {
  group = lint_augroup,
  pattern = opts.autocmd.pattern,
  callback = lint_autocmd,
})

vim.keymap.set("n", "<leader>cl", lint_on_demand, { desc = "[C]ode [l]int" })
```

You could easily add another user command or keybind to adjust the on_demand_linters or auto_linters variables to make it more dynamic.

**Comment by mfussenegger** [comment]
You can setup a keymap or command that either removes the cspell entries from the `linters_by_ft` table or modifies your autocmd.

To clear already existing diagnostics you can call `vim.diagnostic.reset` with the namespace retrieved by `require("lint").get_namespace("cspell")`
