### ISSUE TITLE
(eslint) Question: How to hide names of rules?

### ISSUE THREAD

**Issue by nikitarevenco** [mfussenegger/nvim-lint#615]
Hi, I just wanted to ask if its possible to disable showing the name of each rule?
eg "@typescript-eslint/no-unused-vars" should be hidden and "tailwindcss/enforces-shorthand" should also be hidden ideally.

It's just a bit obstructive and I would rather just be able to see the message.

![image](https://github.com/mfussenegger/nvim-lint/assets/154856872/e071751b-8780-420c-9b19-1659b6074ce6)

Thanks!

**Comment by mfussenegger** [comment]
The screenshot you're shows a diagnostic display that's probably from some other plugin.

To configure the built-in diagnostic display you can have a look at `:help vim.diagnostic.config()`. You're probably looking at disabling the `source` option.
