### ISSUE TITLE
from_pattern does not set source

### ISSUE THREAD

**Issue by dfn-certling** [mfussenegger/nvim-lint#62]
From the documentation of `from_pattern` in README.md and the usage in multiple linters, it looks like `from_pattern` is supposed to accept a source setting in `defaults` that should be included in the generated diagnostics.

This does not seem to work as `from_pattern` only uses values from `defaults` for severity values or if there is a corresponding `group_handler`. Maybe a `group_handler` like the following is the only thing missing here as the source shouldn't be entry specific:

```lua
source = function(entries)
  return defaults['source']
end
```

**Comment by mfussenegger** [comment]
It applies the default values here: 

https://github.com/mfussenegger/nvim-lint/blob/51070c99771d42a7e42b56c3e6541ebc42ba82c6/lua/lint/parser.lua#L95-L96

Also added a test-case for it: https://github.com/mfussenegger/nvim-lint/pull/63


Keep in mind that so far neovim core by doesn't display include the source information in most diagnostic display functions.

**Comment by dfn-certling** [comment]
Ah, yes, thanks! Should have updated my copy before checking =). Sorry for the noise.

I know about core not displaying the source, I wrote my own diagnostic popup for that.
