### ISSUE TITLE
How to add support for tslint? 

### ISSUE THREAD

**Issue by AlejandroSanchez90** [mfussenegger/nvim-lint#632]
i been triying to make tslint work with nvim lint, as right now i have to use a separated plugin named ale for this ( we ue tsc at work on a old app) so i would like to be able to get linting while im coding, but only use a single pluging isntead  of 2, is this possible?

**Comment by mfussenegger** [comment]
See https://github.com/mfussenegger/nvim-lint?tab=readme-ov-file#custom-linters
