### ISSUE TITLE
`append_fname` appears to no longer be working

### ISSUE THREAD

**Issue by dyoshida-continua** [mfussenegger/nvim-lint#641]
I had a custom command set up for running pylint, but I started getting "no files to lint" as an error. I replaced my command with the following to check whether pylint was actually being passed the filename.

```lua
local nvim_lint_pylint = require('lint').linters.pylint
nvim_lint_pylint.cmd = 'python'
-- Original command nvim_lint_pylint.args = {'-m', 'pylint', '-f', 'json'}
nvim_lint_pylint.args = {'/tmp/arg_echoer.py'}
nvim_lint_pylint.append_fname = true
```

`/tmp/arg_echoer.py` just spits out the contents of argv. When I save a buffer, I get a log message saying that no arguments were passed through to the script. My configuration was previously working until I updated my plugins today, so I assume something changed.

**Comment by mfussenegger** [comment]
`pylint` was changed to support stdin in https://github.com/mfussenegger/nvim-lint/pull/628

filenames are intentionally not getting appended if `stdin` is true.

**Comment by dyoshida-continua** [comment]
Ah, thanks! Sorry for the spurious issue.
