### ISSUE TITLE
Filtering by path (`actionlint`)

### ISSUE THREAD

**Issue by 9999years** [mfussenegger/nvim-lint#660]
[`actionlint`](https://github.com/rhysd/actionlint) is a linter for GitHub Action workflows. However, if I include it in `linters_by_ft`, `nvim-lint` attempts to lint _all_ `yaml` files with `actionlint`, leading to copious errors if I open any non-GitHub Actions `yaml` file.

Proposal: Let's add another key to `lint.Linter` for filtering whether or not the linter is run on a particular file. Maybe it could get passed the buffer's path, or even just the buffer number and individual linters could resolve it from there.

Keeping the interface simple (a function you pass a buffer number to) will help keep complexity out of the core and push it into the individual linters, hopefully reducing maintenance burden. (I'm pretty mindful of the maintenance burden of the linters after `null-ls` got archived largely for that reason...)

I'd be happy to write the code for this, but I don't want to put in the effort if you're not on board with the design.

**Comment by mfussenegger** [comment]
You can instead do something like this:

```lua
vim.filetype.add({
  pattern = {
    ['.*/.github/workflows/.*%.yml'] = 'yaml.ghaction',
    ['.*/.github/workflows/.*%.yaml'] = 'yaml.ghaction',
  },
})
```

```lua
  local lint = require('lint')
  lint.linters_by_ft = {
    ghaction = {"actionlint"},
  }
```
