### ISSUE TITLE
Linter "biomejs" cannot be resolved into a Mason package

### ISSUE THREAD

**Issue by jbolila** [mfussenegger/nvim-lint#669]
Biome is registered differently on Mason https://mason-registry.dev/registry/list?search=biome#biome and here in this project.

This is causing issues in the integration between different plugins, e.g. 

```
[mason-nvim-lint] Linter "biomejs" cannot be resolved into a Mason package. Make sure to only provide valid linter names.
```

Thanks

**Comment by mfussenegger** [comment]
I don't see how that's a problem for nvim-lint. mason-nvim-lint needs to update it's mapping or whatever it has.
