### ISSUE TITLE
Use a path for linter

### ISSUE THREAD

**Issue by Domas-Vaitmonas** [mfussenegger/nvim-lint#67]
How can I provide a path to a linter?

I currently have this:

`require('lint').linters_by_ft = {
    python = {'flake8',}
}`

However, I would like to provide a path for this filetype, like this:

`require('lint').linters_by_ft = {
    python = {'/some/path/to/flake8',}
}`

Is it possible?

Thanks in advance

**Comment by mfussenegger** [comment]
`linters_by_ft` is used to configure which linters to use per filetype. If you want to customize a linter you have to import it and change its properties.

For example:


```lua
require('lint.linters.flake8').cmd = '/some/path/to/flake8'
```

You can see all properties like this:

```vimL
:lua print(vim.inspect(require('lint.linters.flake8')))
```

**Comment by Domas-Vaitmonas** [comment]
Thanks a lot. Worked like a charm
