### ISSUE TITLE
Modifying markdownlint-cli2 properties

### ISSUE THREAD

**Issue by NCura** [mfussenegger/nvim-lint#672]
Hello,

In the `README.md`, it's mentioned that we can modify a linter’s properties like this:

```lua
local phpcs = require('lint').linters.phpcs
phpcs.args = {
  '-q',
  -- Add a new parameter here
  '--report=json',
  '-'
}
```

However, I’m trying to modify the `markdownlint-cli2` linter and I’m unsure of the correct name to use inside the `linters` table. Here’s what I’ve attempted so far:

```lua
-- local markdownlint = require('lint.linters.markdownlint-cli2')
local markdownlint = require('lint').linters['markdownlint-cli2']
markdownlint.args = {
  "-c ~/.markdownlint.json",
}
lint.linters_by_ft = {
  markdown = { "markdownlint-cli2" },
}
```

Unfortunately, it doesn't seem to detect the config file, with neither of the two ways of creating the `markdownlint` variable.

In this [issue](https://github.com/mfussenegger/nvim-lint/issues/174), it was mentioned that `require("lint.linters.phpcs")` was a typo, and the correct syntax should be `require('lint').linters.phpcs`. However, since `markdownlint-cli2` contains a hyphen (`-`), this doesn’t seem to work. Could you clarify the correct approach to modifying linters like `markdownlint-cli2`?

When I run the following command:

```sh
:lua print(vim.inspect(require('lint.linters.markdownlint-cli2')))
```
No args appear. In the declaration of the linter, there is no args, so I assume it's using the default value of {}. Could this be why it’s not detecting my custom args?
  
Thank you!

**Comment by mfussenegger** [comment]
`args` needs to be a list of strings.

```lua
markdownlint.args = {
  "-c ~/.markdownlint.json",
}
```

is settings `-c ~/.markdownlint.json"` was single argument - that's as if you'd quote it in the shell and isn't what you want.


```lua
markdownlint.args = {
  "-c",  vim.fn.expand("~/.markdownlint.json"),
}
```

Using `require('lint').linters['markdownlint-cli2']` should work.
