### ISSUE TITLE
Toggling linting on/off

### ISSUE THREAD

**Issue by IstiCusi** [mfussenegger/nvim-lint#678]
Dear mates,

is there a way to toggle linting on/off. If NOT, this would be great extension to the plugin. 
If YES, could you please point me to the documentation, where the setup is described 
concerning this feature. Thanks a lot, 
Stephan

**Comment by mairs8** [comment]
> `:help vim.diagnostic.enable()`

this toggles all diagnostics. is there any way to toggle just the linting?
