### ISSUE TITLE
how to disable no eslint configuration error? 

### ISSUE THREAD

**Issue by AlejandroSanchez90** [mfussenegger/nvim-lint#679]
Hello, would like to know how can i disable the error when there is no eslint configuration? sometimes i work on apps that dosent havent eslint file, so i get this error on each file that i open
this is my config

```lua
return {
	"mfussenegger/nvim-lint",
	event = { "BufReadPre", "BufNewFile" },
	config = function()
		local lint = require("lint")

		lint.linters_by_ft = {
			javascript = { "eslint_d" },
			typescript = { "eslint_d" },
			javascriptreact = { "eslint_d" },
			typescriptreact = { "eslint_d" },
			svelte = { "eslint_d" },
			python = { "pylint" },
		}

		local lint_augroup = vim.api.nvim_create_augroup("lint", { clear = true })

		vim.api.nvim_create_autocmd({ "BufEnter", "BufWritePost", "InsertLeave" }, {
			group = lint_augroup,
			callback = function()
				lint.try_lint()
			end,
		})

		vim.keymap.set("n", "<leader>l", function()
			lint.try_lint()
		end, { desc = "Trigger linting for current file" })
	end,
}
```

**Comment by frixaco** [comment]
@AlejandroSanchez90 You can try wrapping the `try_lint` call with `pcall`:
(this is from my config btw)
```lua
vim.api.nvim_create_autocmd({ 'BufWritePost' }, {
  callback = function()
    pcall(require, 'lint.try_lint')
  end,
 })
```

In your case, you probably should do `pcall(lint, "try_lint")` instead of `lint.try_lint()`

**Comment by zLinz** [comment]
@frixaco tried but not working

**Comment by AlejandroSanchez90** [comment]
> @frixaco tried but not working 

It should work, or you have linting calls somewhere else, pcall is the equivalent of a try catch block

**Comment by mfussenegger** [comment]
See https://github.com/mfussenegger/nvim-lint/issues/685
