### ISSUE TITLE
[BUG] Warnings in the editor are duplicated when adding clangtidy

### ISSUE THREAD

**Issue by anzix** [mfussenegger/nvim-lint#693]
I checked on the main system with my own nvim config and on a pure EndeavourOS virtual machine using LazyVim

Arch Linux System

neovim v0.10.2

Step to reproduce:

1. Download LazyVim

   ```sh
   git clone https://github.com/LazyVim/starter ~/.config/nvim
   ```

2. Install `clangd` using Mason

3. According to https://www.lazyvim.org/plugins/linting add the file `~/.config/nvim/lua/plugins/nvim-lint.lua` in it spec lines

4. In `~/.config/nvim/lua/plugins/nvim-lint.lua` inside `linters_by_ft` add a line

   ```lua
   c = { "clangtidy" },
   ```

5. Open the working code in C and repeated warnings appear

```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(void) {
  char *p = malloc(4);
  free(p);
  p = NULL;  // To avoid problems with a dangling pointer
  strcpy(p, "abc"); // You will get a segfault, because there is an assignment to the null pointer
  return EXIT_SUCCESS;
}
```

Here is the `.clang-tidy` file inside my project with my checks

```yaml
---
Checks: >
  -*,
  cert-*,
  clang-*,
  clang-analyzer-*,
  readability-*,


# Turn all the warnings from the checks above into errors.
WarningsAsErrors: ""
```

Duplicate warnings

```txt
Diagnostics:
1. Variable name 'p' is too short, expected at least 3 characters [readability-identifier-length]
2. variable name 'p' is too short, expected at least 3 characters 
```

```txt
Diagnostics:
1. Null pointer passed to 1st parameter expecting 'nonnull' 
2. Null pointer passed to 1st parameter expecting 'nonnull'
3. Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119 
4. Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119
```

![Снимок экрана в 2024-10-31 00-26-00](https://github.com/user-attachments/assets/e8869d34-f0a4-436a-af36-586753331f33)
![Снимок экрана в 2024-10-31 00-26-21](https://github.com/user-attachments/assets/54b753ac-50ec-45d2-955c-775f0816aa14)

An interesting note: By adding the file `.clang-tidy` string `WarningsAsErrors: "*"` one of the duplicated messages changes color from yellow to red

**Comment by mfussenegger** [comment]
This might be the language server providing the same diagnostics?
nvim-lint isn't duplicating diagnostics.
