### ISSUE TITLE
Modifying a builtin linter without reduced form consider it as a new linter

### ISSUE THREAD

**Issue by HeitorAugustoLN** [mfussenegger/nvim-lint#703]
```lua
{
  "nvim-lint",
  after = function()
    local lint = require("lint")
    lint.linters_by_ft = { nix = { "statix" } }
    lint.linters.fake_statix = {
      args = { "check", "-o", "errfmt", "--stdin" },
      cmd = "/nix/store/pkqp4is8aybllw37406hb3n0081jdhgq-statix-0.5.8/bin/statix",
      ignore_exitcode = true,
      parser = require("lint.parser").from_errorformat("<stdin>>%l:%c:%t:%n:%m", {
        source = "statix",
      }),
      stdin = true,
      stream = "stdout",
     }
     lint.linters.statix = { cmd = "/nix/store/pkqp4is8aybllw37406hb3n0081jdhgq-statix-0.5.8/bin/statix" }
  end,
  event = { "BufNewFile", "BufReadPost", "BufWritePost" },
 },
```

I've been setting nvim-lint with lz.n like this, but for some reason, I don't know if this is intentional, but when trying to modify statix without the reduced form (`lint.linters.statix.cmd`), the plugin considers that I am creating a new linter, just like I did with fake_statix, instead of modifying a builtin one.

**Comment by mfussenegger** [comment]
See https://github.com/mfussenegger/nvim-lint/pull/704#issuecomment-2553399202 and https://github.com/mfussenegger/nvim-lint?tab=readme-ov-file#customize-built-in-linters
