### ISSUE TITLE
How to iterate current buffer linters with their id's to draw their summary in status line?

### ISSUE THREAD

**Issue by vatosarmat** [mfussenegger/nvim-lint#81]
Hello. Thank you for the plugin. I think direct spawning of `linter.cmd` and reading from its stdout is better than spawning intermediate headless neovim instances like other plugins do.
To draw diagnostics summary in status line, I use `vim.lsp.diagnostic.get_count(0, severiry, client_id)` which requires `clinet_id`. But it seems there is no way to get `client_id` from `nvim-lint` except looking in its code and finding `local CLIENT_ID_OFFSET = 1000`. Maybe there should be some public API?

**Comment by mfussenegger** [comment]
Do you need to distinguish the counts by the client? If not you could call `vim.lsp.diagnostic.get_count(0, severity)` to get the sum over all clients.

`CLIENT_ID_OFFSET` is currently a hack and I would like this avoid exposing that.

**Comment by vatosarmat** [comment]
Yes, I think separation of counts(and other LSP info e.g. progress messages) by client is a nice feature to have and should be easy to implement

**Comment by vatosarmat** [comment]
hope this will do the tricks without dirty hacks, thanks
