### ISSUE TITLE
Cppcheck >1.84 required ({column} required)

### ISSUE THREAD

**Issue by tsjordan-eng** [mfussenegger/nvim-lint#87]
Can we add a note in the readme that states `cppcheck` version 1.84 or greater is required? I went through a lot of debugging to find out that 1.82 that in Ubuntu's repo doesn't support `{column}` in the template argument. No indication was given by nvim-lint that cppcheck was failing.
 (Is there a good way to debug this tool and the parser? LspInfo doesn't show anything.)

**Comment by tsjordan-eng** [comment]
I'm trying to solve this problem in #88

**Comment by mfussenegger** [comment]
https://github.com/mfussenegger/nvim-lint/pull/88 got merged
