### ISSUE TITLE
Markdownlint is not working on windows

### ISSUE THREAD

**Issue by ok97465** [mfussenegger/nvim-lint#89]
Hello.

Thank you for your great works.

I have been using markdownlint of nvim-lint on Linux.
But the following error appears and it doesn't work normally on windows.

```
lint.lua:162: Error running markdownlint: ENOENT: no such file of directory
```

So I replaced "markdownlint" with "markdownlint.cmd" in the following code.

https://github.com/mfussenegger/nvim-lint/blob/02c490812f73408b31fac122b32306a6f2e7ce49/lua/lint/linters/markdownlint.lua#L3-L4

Then a console window only blinks and the lint does not work.

![Animation](https://user-images.githubusercontent.com/22970578/132041516-47d0e70c-098a-4b86-bcaf-a47116450b4c.gif)

Thank you for reading. Have a good day.

**Comment by mfussenegger** [comment]
Does `markdownlint.cmd` return the linter output on stdout or stderr? It sounds as if it is spawning the terminal that is actually running the linter, and therefore nvim-lint doesn't receive the results.

**Comment by ok97465** [comment]
I think that ```markdownlint.cmd``` returns the linter output on stdout.

![image](https://user-images.githubusercontent.com/22970578/132691029-d4aa4bd5-3f48-45c0-af72-cfb70b948616.png)

**Comment by mfussenegger** [comment]
I assume this is fixed.  Please reopen otherwise

**Comment by ok97465** [comment]
I'm sorry. I missed the notification. 

The markdownlint is working properly if "markdownlint" is replaced with "markdownlint.cmd" in the following code on windows.

https://github.com/mfussenegger/nvim-lint/blob/02c490812f73408b31fac122b32306a6f2e7ce49/lua/lint/linters/markdownlint.lua#L3-L4

Thank you very much.

**Comment by mfussenegger** [comment]
Changed the default: https://github.com/mfussenegger/nvim-lint/pull/134
