### ISSUE TITLE
vim.schedule uri nil value

### ISSUE THREAD

**Issue by lawrencet149** [mfussenegger/nvim-lint#90]
Hi,

Thank you for all the work on nvim-lint. 

I am getting an error when saving a file after updating nvin-lint to latest version. Linting was working prior to the update. 

"Error executing vim.schedule lua callback: .../.local/nvim/share/nvim/runtime/lua/vim/uri.lua:116: attempt to index local 'uri' (a nil value)" 

Config:
require("lint").linters_by_ft = {
    python = {
        "pylint",

    }
}

vim.cmd("au BufWritePost <buffer> lua require('lint').try_lint()")

**Comment by lawrencet149** [comment]
Fix with upgrade to nvim nightly release.

**Comment by mfussenegger** [comment]
If you used nvim 0.5 before it should also work again with https://github.com/mfussenegger/nvim-lint/pull/91
