### ISSUE TITLE
Error executing vim.schedule lua callback with latest Neovim nightly

### ISSUE THREAD

**Issue by jonasstr** [mfussenegger/nvim-lint#95]
Hey, I just upgraded from the 0.5 stable version to the latest nightly build (NVIM v0.6.0-dev+284-gc2a65921d) from commit [c2a6592](https://github.com/neovim/neovim/commit/c2a65921d762929a1b8e740aeb92c7970d025736). I also have the latest nvim-lint version.

Since then I always get this error when I open a Python file (I have an autocmd that calls `try-lint()` on `BufEnter`):
```vim
Error executing vim.schedule lua callback: vim/shared.lua:225: after the second argument: expected table, got number
stack traceback:
        vim/shared.lua:225: in function 'tbl_deep_extend'
        ....mount_nvimJNlEFY/usr/share/nvim/runtime/lua/vim/lsp.lua:1502: in function <....mou
nt_nvimJNlEFY/usr/share/nvim/runtime/lua/vim/lsp.lua:1501>
        /home/jonas/.vim/plugged/nvim-lint/lua/lint.lua:51: in function 'cb'
        vim.lua:281: in function <vim.lua:281>
```
Can you help with this? Thanks in advance.

**Comment by mfussenegger** [comment]
https://github.com/neovim/neovim/pull/15585 was merged yesterday and it contained a couple of bugs + I didn't have time to adjust/test nvim-lint yet.

**Comment by Groctel** [comment]
I just tried using the linter again with the latest nvim even tough you haven't pushed any changes and it's working as usual. Here's my `nvim -v`:

```
NVIM v0.6.0-dev+313-g490e09c6d
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions     -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security     -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/groctel/.cache/yay/neovim-git/src/build/config -I/home/groctel/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/groctel/.cache/yay/neovim-git/src/build/src/nvim/auto -I/home/groctel/.cache/yay/neovim-git/src/build/include
Compiled by groctel

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

And here's my `nvim-lint` settings:

```lua
require('lint').linters_by_ft = {
	sh = {'shellcheck'},
}
```

**Comment by jonasstr** [comment]
@Groctel I just tested it and for me it's not working yet with the latest `NVIM v0.6.0-dev+304-g924e8e4f2` so I will keep this issue open.

**Comment by mfussenegger** [comment]
@jonasstr can you share your `vim.lsp.with` overrides for the diagnostic handler? (Judging from `nvim/runtime/lua/vim/lsp.lua:1501` you're customising it)

**Comment by jonasstr** [comment]
I did not specifically change `vim.lsp.with`. Maybe some plugin did this? In case this helps you can check out my config [here](https://github.com/jonasstr/dotfiles/tree/master/.config/nvim).

**Comment by mfussenegger** [comment]
You've 

```
lsp.handlers["textDocument/publishDiagnostics"] = lsp.with(
    lsp.diagnostic.on_publish_diagnostics, {
        virtual_text = false
    }
)
```

In there which seems okay. Works for me with both nvim 0.5 and with latest neovim master

**Comment by jonasstr** [comment]
Well, you're right, I did not remember this. Do you have any ideas for what might be causing this if there is no problem with `lsp.with`?

**Comment by mfussenegger** [comment]
No idea but seems to be an issue with your configuration or setup. Maybe you're still pointing $VIMRUNTIME to the 0.5 location or something like that.

**Comment by Groctel** [comment]
Is `NVIM v0.6.0-dev+304-g924e8e4f2` the latest version you can get? As I said earlier upgrading to the latest `HEAD` fixed it for me, which suggests this issue comes from a core nvim bug that was already patched.

**Comment by jonasstr** [comment]
I just tested it again with the latest currently available app image ([link](https://github.com/neovim/neovim/actions/runs/1268574605)), this did not fix it. `nvim -v` prints:
```
NVIM v0.6.0-dev+336-g433bda405
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az139-151
```

**Comment by jonasstr** [comment]
Ok guys, this is dumb. I had created a nvim-lint fork to test some minor stuff and I did not notice I was using the fork until now... The fork did not contain the commit that has already fixed this.
